プレイヤーの移動関係の基礎を作成
InnovaGameCreate/mythos-encounter pull request #10
Opened 2024-04-13 23:19 UTC by IwamotoHinata

## 概要

## 変更点

## テスト

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

2024-04-13 23:38 UTC, IwamotoHinata commented
![スクリーンショット 2024-04-14 082145](https://github.com/InnovaGameCreate/mythos-encounter/assets/86921212/fb9963dc-c9eb-4dc2-8b44-22a8aa127735)

2024-04-14 01:09 UTC, Tyunousause requested changes
カメラの揺れる機能に問題あり。
一度でも歩くと待機状態でカメラの位置がアンダーシュートする。例として待機状態でカメラy座標が2.48になってしまった
原因はおそらくDotWeenのSequenceの始点がオブジェクトの現在の座標であるという事。そのため移動状態がy座標2.48などの値で終了すると待機状態でもy座標が2.48になる。
また待機状態でのサイクルが倍の時間かかってしまっている

2024-04-14 02:10 UTC, Tyunousause requested changes
状態が変わった瞬間カメラがカクッと動くけど想定内の動きはする

2024-04-14 02:10 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Player/CameraMove.cs
> +                sequence.Play().SetLoops(-1, LoopType.Yoyo);
```ruby
                sequence.Append(this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y, 0), 0));
                sequence.Append(this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y - _offSet / 2, 0), cycle / 2));
                sequence.Append(this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y, 0), cycle / 2));
                sequence.Play().SetLoops(-1, LoopType.Restart);
```

2024-04-14 02:10 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Player/CameraMove.cs
> +            sequence.Play().SetLoops(-1, LoopType.Yoyo);
```ruby
            sequence.Append(this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y, 0), 0));
            sequence.Append(this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y - _offSet, 0), clipTime / 2));
            sequence.Append(this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y, 0), clipTime / 2));           
            sequence.Play().SetLoops(-1, LoopType.Restart);     
```

2024-04-14 06:25 UTC, tibigamePoppo approved these changes

2024-04-14 06:25 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/CameraMove.cs
> +            sequence.Play().SetLoops(-1, LoopType.Yoyo);
```suggestion
sequence.Kill();
            float initialPositonTime = Mathf.Abs(_idleCycle *(_cameraPositionDefault.y - this.transform.position.y)/_offSet );//現在地から最初のカメラの位置に戻すまでの時間の計算
            this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y, 0), initialPositonTime);//最初にカメラをDefaultの位置に戻す

            sequence = DOTween.Sequence();
            sequence.SetDelay(initialPositonTime);///最初にカメラをDefaultの位置に戻すまで、シーケンスを待機させる

            //動かない状態の時は引数に0を入れている
            //待機状態ではほんの少しだけゆっくりと視点が変わる
            if (clipTime == 0)
            {
                sequence.Append(this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y - _offSet / 2, 0), _idleCycle / 2));
                sequence.Append(this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y, 0), _idleCycle / 2));
                sequence.Play().SetLoops(-1, LoopType.Yoyo);

                return;
            }
            

            //今回設定する挙動を作成
            sequence.Append(this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y - _offSet, 0), clipTime / 2));
            sequence.Append(this.transform.DOLocalMove(new Vector3(0, _cameraPositionDefault.y, 0), clipTime / 2));
            sequence.Play().SetLoops(-1, LoopType.Yoyo);     
``` 
カメラを最初に初期位置に戻す理とシーケンスの初期化が共通しているので最初に持ってくるのはどうでしょう。
また、現在カメラを初期位置に戻すのを0秒でやっているのがカクツク原因になっているため、初期位置と現在の位置で戻すまでの時間を計算して、その時間で戻すようにするのはどうでしょう。

2024-04-14 06:31 UTC, tibigamePoppo requested changes
ミスってApproveしたため、RequestChangesに変更します。

2024-04-14 19:09 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Player/CameraMove.cs
> +            sequence.Play().SetLoops(-1, LoopType.Yoyo);
改善案を考えてくださりありがとうございます‼
実際にやってみるとカクツキはなくなりました。
しかし足音と振動がリンクしないようになってしまいました...。（移動中に視点がデフォルトの座標に固定される時間が発生する等）
将来的にはアニメーションイベントを用いて足音と振動を実装しようと考えているので、α版は遠藤先輩が提案してくださった方法でいこうと考えてます。

2024-04-14 19:56 UTC, IwamotoHinata commented
## 変更点
- **プレイヤー操作の方で以下の問題が発生していたので修正しました。**
- WS , ADの同時押しの際動かないのに状態が「Idle」になっておらず、足音が鳴る
- ダッシュ状態時にWキーを離していてもASDのどれかを押していたら、対応する方向にダッシュする

2024-04-14 22:53 UTC, tibigamePoppo approved these changes
スクリプト、エラーの確認をしました。

2024-04-14 23:56 UTC, Tyunousause approved these changes

2024-04-14 23:57 UTC, Tyunousause reviewed
問題なくシーン再生可能を確認。動作スクリプトも問題無し。

2024-04-15 00:13 UTC, merged