HPゲージをartの素材にあるものに変更
InnovaGameCreate/mythos-encounter pull request #103
Opened 2024-07-04 19:00 UTC by twink-star

## 概要
素材をインポートした

## 変更点
- スタミナゲージ、HPゲージ、アイテムスロットをインポート
- ItemImageをアクティブに

## テスト
 
 動作確認用シーン：InGame

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [x] ビルドが成功するかの確認
## 問題
- 本来透けて見えるアイテムが、透けていない

2024-07-06 13:47 UTC, Tyunousause reviewed
@twink-star 
私の環境では以下のエラーが出るのですがそちらではどうでしょうか？
NullReferenceException: Object reference not set to an instance of an object
Scenes.Ingame.Player.PlayerGUIPresenter.<Awake>b__19_3 (System.String x) (at Assets/Scripts/Scenes/InGame/Player/PlayerGUIPresenter.cs:134)
UniRx.Observer+Subscribe`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/Observer.cs:165)
UniRx.Subject`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/Subjects/Subject.cs:62)
Scenes.Ingame.Player.PlayerItem+<>c__DisplayClass22_0.<Start>b__0 (UniRx.Unit _) (at Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs:88)
UniRx.Observer+Subscribe`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/Observer.cs:165)
UniRx.InternalUtil.ListObserver`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/InternalUtil/ListObserver.cs:39)
UniRx.Subject`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/Subjects/Subject.cs:62)
UniRx.Triggers.ObservableUpdateTrigger.Update () (at Assets/Plugins/UniRx/Scripts/UnityEngineBridge/Triggers/ObservableUpdateTrigger.cs:14)

2024-07-09 23:23 UTC, tibigamePoppo commented
> @tibigamePoppo @IwamotoHinata 私の環境では以下のエラーが出るのですがそちらではどうでしょうか？ NullReferenceException: Object reference not set to an instance of an object Scenes.Ingame.Player.PlayerGUIPresenter.b__19_3 (System.String x) (at Assets/Scripts/Scenes/InGame/Player/PlayerGUIPresenter.cs:134) UniRx.Observer+Subscribe`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/Observer.cs:165) UniRx.Subject`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/Subjects/Subject.cs:62) Scenes.Ingame.Player.PlayerItem+<>c__DisplayClass22_0.b__0 (UniRx.Unit _) (at Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs:88) UniRx.Observer+Subscribe`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/Observer.cs:165) UniRx.InternalUtil.ListObserver`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/InternalUtil/ListObserver.cs:39) UniRx.Subject`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/Subjects/Subject.cs:62) UniRx.Triggers.ObservableUpdateTrigger.Update () (at Assets/Plugins/UniRx/Scripts/UnityEngineBridge/Triggers/ObservableUpdateTrigger.cs:14)

同様のエラーはおきます。おそらくPlayerGUIPresenterのItemPopとItemPop_textがアタッチされていないのが原因だと思います

2024-07-09 23:24 UTC, tibigamePoppo commented
スタミナ、HP、SANですが、サイズをサイズを変更するのではなくFillAmountを使った減少に切り替えてほしいです。

2024-07-09 23:24 UTC, tibigamePoppo requested changes
スタミナ、HP、SANですが、サイズをサイズを変更するのではなくFillAmountを使った減少に切り替えてほしいです。

2024-07-11 08:17 UTC, Hiraki-Shunsuke commented
@tibigamePoppo こちらのタスクですが、木村君と相談して巻き取りました。
別個でプルリクを作成するので、こちらのプルリクは閉じてください

2024-07-11 16:03 UTC, closed without merging