ステージ生成機能の実装
InnovaGameCreate/mythos-encounter pull request #11
Opened 2024-04-16 15:30 UTC by tibigamePoppo

## 概要

ステージ生成機能の実装
仮置き用の部屋プレファブ
![stage1](https://github.com/InnovaGameCreate/mythos-encounter/assets/67269447/0e6379cf-cc4e-48d1-8032-13577843fefc)
![stage2](https://github.com/InnovaGameCreate/mythos-encounter/assets/67269447/2c711064-7562-4333-bb9d-8329c1ab9a39)

## 変更点

- 開発シーンIngame_Stageの追加
- ステージ生成機能の実装
- ステージ生成機能のテスト用スクリプトの作成
- ステージ生成用の各種大きさの部屋の作成

## テスト

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

- 出来るだけまとめましたが、複雑な構造になっているため、今後リファクタリングを行う予定です
- 通路生成後、新しく孤立する空間（2x1や3x1の小さな空間）ができる。今後対応予定

2024-04-16 20:11 UTC, IwamotoHinata reviewed
シーンの再生を確認しました。エラーもなかったです。
![スクリーンショット 2024-04-17 050417](https://github.com/InnovaGameCreate/mythos-encounter/assets/86921212/7c1c39ad-4728-461e-b97d-9fd87cd0abd7)
何回か自動生成したのですが、キャラのスポーン地点付近に通路がなく詰んでいるパターンが割とありました。

2024-04-16 20:20 UTC, IwamotoHinata submitted a review, later dismissed
Commentのままにしてました

2024-04-16 22:09 UTC, tibigamePoppo commented
現状部屋のバリエーションが無く、通路が無くて詰んでいる状況は発生してしまいます。
そのため、部屋のバリエーションを増やして、対応する予定です。

2024-04-17 00:06 UTC, tibigamePoppo commented
応急処置になりますが、現在の素材の部屋のドアの数を増設しておきました

2024-04-19 08:52 UTC, Tyunousause requested changes
ステージのサイズを10*10にしたところエラーが発生
StageGanarater.cs行数179
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

2024-04-19 11:37 UTC, tibigamePoppo commented
@Tyunousause 
[092c3c4](https://github.com/InnovaGameCreate/mythos-encounter/pull/11/commits/092c3c47d3719e2c3c0895048aad4ebbb951ff66)
修正しました

2024-04-19 12:36 UTC, Tyunousause approved these changes
小さく設定しても無事に作動することを確認しました。

2024-04-19 12:38 UTC, Tyunousause approved these changes

2024-04-19 13:01 UTC, merged