試遊会へ向けたステージの調整
InnovaGameCreate/mythos-encounter pull request #118
Opened 2024-07-12 14:42 UTC by tibigamePoppo

## 概要

ステージサイズを4割に削減、NavMeshの修正
## 変更点

- インスペクターからステージの生成数を調整できるように機能追加
- Ingameのステージの大きさを変更
- NavMeshがつながらない問題の修正
## テスト
 
 動作確認用シーン：

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-07-12 15:43 UTC, Tyunousause requested changes
EnemySpownerのxとzも一緒に小さくしてほしいです

2024-07-13 04:37 UTC, tibigamePoppo commented
> 18e5dcd

[18e5dcd](https://github.com/InnovaGameCreate/mythos-encounter/pull/118/commits/18e5dcda7c1803fd8477cf484a87507b96bfdf8e)
修正しました

2024-07-13 04:37 UTC, tibigamePoppo commented
> EnemySpownerのxとzも一緒に小さくしてほしいです

[18e5dcd](https://github.com/InnovaGameCreate/mythos-encounter/pull/118/commits/18e5dcda7c1803fd8477cf484a87507b96bfdf8e)
修正しました

2024-07-13 20:24 UTC, Tyunousause approved these changes
正しく設定されていることを確認しました

2024-07-14 04:05 UTC, IwamotoHinata approved these changes

2024-07-14 04:05 UTC, merged