ステージプレハブのIssueの修正
InnovaGameCreate/mythos-encounter pull request #119
Opened 2024-07-12 14:55 UTC by Hiraki-Shunsuke

## 概要
ステージプレハブに関係する不具合の修正
## 変更点
- 照明についていたURP関係のコンポーネントの削除
- ドアの生成位置によって侵入不能になるプレハブの修正
- テクスチャが重なって表示がおかしくなっているオブジェクトを修正
## テスト
動作確認用シーン：InGame
 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認

2024-07-12 16:00 UTC, Tyunousause reviewed
チラチラの解消と、詰む位置の家具の削除を確認

2024-07-12 16:00 UTC, Tyunousause approved these changes

2024-07-13 04:21 UTC, IwamotoHinata requested changes
![スクリーンショット 2024-07-13 131934](https://github.com/user-attachments/assets/d8b2064c-96a2-43bd-b676-0c457822e894)

細かい内容ですみません。
新聞紙のオブジェクトが床に埋まってました。y座標を調整したら出現したので調整をお願いします。
装飾品がバグる...のやつです

2024-07-13 08:32 UTC, Hiraki-Shunsuke commented
@IwamotoHinata 
確認ありがとう
こっちで検証したら2階部分の床が1階部分と比べて少し高く生成されてるっぽい
だから2階に生成される全部屋の薄いオブジェクト埋まってた
2階の床がY0.06くらい下げて座標を5.84くらいにしたらちょうどよかった
@tibigamePoppo 2階の床の高さはすぐに変更可能な要素ですか？

2024-07-13 11:52 UTC, tibigamePoppo commented
> @IwamotoHinata 確認ありがとう こっちで検証したら2階部分の床が1階部分と比べて少し高く生成されてるっぽい だから2階に生成される全部屋の薄いオブジェクト埋まってた 2階の床がY0.06くらい下げて座標を5.84くらいにしたらちょうどよかった @tibigamePoppo 2階の床の高さはすぐに変更可能な要素ですか？

https://github.com/InnovaGameCreate/mythos-encounter/blob/37a7e62c343db9672a3e85a940ace80465865131/Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs#L133

ここを変更すれば簡単に変えれます。ただ、その場合は照明などが床を貫通しないか確認する必要があります

2024-07-13 12:57 UTC, Hiraki-Shunsuke commented
@tibigamePoppo 元の状態で一個貫通してるオブジェクトを発見しましたが、修正に時間かかりそうなので一旦この修正で確認お願いします。
モデル自体をちょっと弄る必要がありそうです。

2024-07-13 20:19 UTC, tibigamePoppo approved these changes

2024-07-13 20:26 UTC, Tyunousause approved these changes
すべて修正せず通すことを確認しました

2024-07-13 20:28 UTC, tibigamePoppo approved these changes

2024-07-14 04:04 UTC, IwamotoHinata approved these changes

2024-07-14 04:04 UTC, merged