身代わり人形実装
InnovaGameCreate/mythos-encounter pull request #130
Opened 2024-07-15 21:10 UTC by nishimura765

## 概要

プレーヤー用のサポートアイテム「身代わり人形」を実装しました。
## 変更点

変更点1 Doll.prefabを追加
変更点2 PlayerItem,PlayerStatus,EnemyMoveを編集
変更点3 GameObjectにEnemyTagを追加
## テスト
 
 動作確認用シーン：Ingame

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-07-15 21:38 UTC, nishimura765 commented
失礼します。
プルリクエストを出した後に気づいたのですが、最新ブランチに死亡時のアニメーションが追加されていました。
このブランチではアニメーションに対応していないのですが、一度rebaseして対応させたほうがよろしいでしょうか？

2024-07-17 01:34 UTC, tibigamePoppo commented
> 失礼します。 プルリクエストを出した後に気づいたのですが、最新ブランチに死亡時のアニメーションが追加されていました。 このブランチではアニメーションに対応していないのですが、一度rebaseして対応させたほうがよろしいでしょうか？

そうですね。
今回ですと、今回ですと死亡アニメーションが発生するためにアイテムの効果を発生させる必要がありそうです。

2024-07-17 19:45 UTC, nishimura765 commented
わかりました。
対応させてコンフリクトを解消した後、再度リクエスト致します。

2024-07-18 02:53 UTC, nishimura765 commented
対応完了いたしました。

2024-07-18 03:43 UTC, IwamotoHinata requested changes
すみません。いくつか修正してほしい箇所があるので箇条書きで書いていきます。

1. 蘇生時は蘇生時用のアニメーションを用意してほしい
→立ち上がるようなアニメーションを用いてほしいです。
　
2. 死亡時のアニメーションは従来のものを使ってほしい。
→死亡後すぐにイベントを呼ばないとアニメーションに沿って当たり判定が遷移しないため。

2024-07-18 03:53 UTC, IwamotoHinata requested changes

2024-07-18 03:53 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemInstract.cs
> -            effect.OnPickUp();//�e�A�C�e���̏E�������̏��������s������
これを消すと他のアイテムが使えなくなるので消さないでほしいです。

今回の身代わり人形のOnPickUp関数でPlayerStatusに人形の数をカウントさせてると思うのですが、以下の方法に変えるのはいかがでしょうか？
1. 死亡アニメーション終了時にアイテムスロットを確認。
2. 身代わり人形があれば蘇生アニメーションを再生し、蘇生時の処理を行う

2024-07-18 04:00 UTC, nishimura765 commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemInstract.cs
> -            effect.OnPickUp();//�e�A�C�e���̏E�������̏��������s������
アドバイスありがとうございます。
再度修正いたします。

2024-07-18 12:11 UTC, IwamotoHinata submitted a review, later dismissed
@tibigamePoppo @Tyunousause 
アニメーション遷移に少しラグがあることを確認しましたが、これは僕の指示によるものです。
後日僕の方で修正する予定なので気にしないでもらえるとありがたいです。

2024-07-18 12:12 UTC, IwamotoHinata submitted a review, later dismissed
@tibigamePoppo @Tyunousause 
アニメーション遷移に少しラグがあることを確認しましたが、これは僕の指示によるものです。
後日僕の方で修正する予定なので気にしないでもらえるとありがたいです。

https://github.com/orgs/community/discussions/58535
2つ上の「The merge-base changed after approval.」が気になって調べてみました。もしマージができなかったら参考にしてください。

2024-07-18 12:40 UTC, IwamotoHinata approved these changes

2024-07-18 21:50 UTC, tibigamePoppo approved these changes

2024-07-18 21:53 UTC, tibigamePoppo approved these changes

2024-07-18 22:57 UTC, Tyunousause requested changes
身代わり人形が使用された後のアイテムスロットの見た目が他と違います。(ItemImageオブジェクトのSourceImageがNoneになっているようです)
また、二つ身代わり人形を持っている場合一回目の死は正常に動作しますが二回目の死では復活ができません。

2024-07-18 22:57 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/DollEffect.cs
> +            }
敵は1体とは限らないのでGameObject.FindGameObjectsWithTag("Enemy")などを使って複数所得してください

2024-07-18 22:57 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/DollEffect.cs
> +            }
ターゲティングが切れていないようですがそこは私がやっておきます

2024-07-18 23:09 UTC, nishimura765 commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/DollEffect.cs
> +            }
了解です。
再度修正いたします。

2024-07-19 04:14 UTC, IwamotoHinata approved these changes

2024-07-21 02:22 UTC, Tyunousause approved these changes
修正されており問題なく機能することを確認しました

2024-07-21 02:22 UTC, merged