コンパス実装
InnovaGameCreate/mythos-encounter pull request #156
Opened 2024-08-17 08:37 UTC by nishimura765

## 概要

プレーヤーアイテムのコンパスを実装しました。
遅くなって申し訳ないです。
## 変更点

変更点1　itemPrefabにcompass(取得前のドロップ状態)とusingCompass(取得後の画面表示用)を追加しました
変更点2　PlayerItemスクリプトを少し編集しました　
変更点3　Player.PrefabのMainCameraに、usingCompassを子オブジェクトとして付属させました
## テスト
 
 動作確認用シーン：Ingame

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

問題点1 usingCompassが他のオブジェクトに隠れて見えなくなる時がある。
　　　　色々調べてみると、コンパスのshader設定を調整することで解決しそうですが、shaderについての知識が乏しいため　
　　　　上手くできませんでした。一応、Compassフォルダ内にshaderをいじったコンパスをおいてます。これでやると他　　　　　　　　　　　　　
　　　　のオブジェクトに多少隠れなくなりますが、表示のぶれなどが起こりかなり不安定になります。

2024-08-20 07:32 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/Compass/CompassMove.cs
> +    private GameObject[] _Enemys;
```suggestion
    private GameObject[] _enemys;
```
_escapePointが小文字始まりなので、こちらも同じようにお願いします。

2024-08-20 07:32 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/Compass/CompassMove.cs
> +        _escapePoint = GameObject.Find("escapePoint(Clone)");
```suggestion
        _escapePoint = GameObject.FindGameObjectsWithTag("EscapePoint");
```
現状のままだと、オブジェクトの名前が変わった際にエラーが起きるため別の方法で取得してください。
※オブジェクトの名前は特に変わりやすいので

2024-08-20 07:32 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/Compass/CompassMove.cs
> +        }
```suggestion
#if UNITY_EDITOR
        if (Input.GetKeyDown(KeyCode.T))
        {
            Debug.Log($"�G�Ƃ̋�����{distance}");
            Debug.Log($"�R���p�X�̊p�x{this.transform.localEulerAngles.y}");

        }

        if (Input.GetKeyUp(KeyCode.L))
        {
            _Enemys = GameObject.FindGameObjectsWithTag("Enemy");

        }
#endif
```
デバック用の機能だと思います。一応Unityエディタ上のみ動作するように設定してください。

2024-08-20 07:32 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/Compass/CompassMove.cs
> +        if (distance >= _unusableDistance)
```suggestion
           if (_enemy.Any(enemy => Vector3.Distance(enemy.transfrom.position,this.transform.position) >= _unusableDistance))
```
こんな感じにLinqの機能を使えばもう少しシンプルに書けそうです。
※動作確認をしていないので、もしかしたらエラーが出るかも
Linqについて → https://www.fenet.jp/dotnet/column/language/2162/

2024-08-22 07:56 UTC, tibigamePoppo approved these changes
スクリプトを見た限りは問題なさそう。

2024-08-22 15:47 UTC, IwamotoHinata requested changes

2024-08-22 15:47 UTC, IwamotoHinata commented on Assets/Resources/Prefab/Stage/escapePoint.prefab
> +  m_TagString: EscapePoint
@tibigamePoppo 
脱出地点のTagが変更されているのですが、これって脱出できなくなってしまうのではないでしょうか？
このプレハブに子オブジェクトを追加で生成して(Create Empty)、子オブジェクトのタグをEscapePointにしたらいいと思います.

2024-08-22 15:57 UTC, IwamotoHinata commented
コンパスの動作自体は確認できました。
敵に近づいたときに壊れること, 脱出地点を指していること, 問題なかったです！

2024-08-23 02:38 UTC, tibigamePoppo commented on Assets/Resources/Prefab/Stage/escapePoint.prefab
> +  m_TagString: EscapePoint
確かに、一応そうした方が良いですね。

2024-08-23 02:48 UTC, nishimura765 commented on Assets/Resources/Prefab/Stage/escapePoint.prefab
> +  m_TagString: EscapePoint
了解です。

2024-08-27 03:16 UTC, IwamotoHinata approved these changes

2024-08-27 03:16 UTC, merged