作業統合4/19
InnovaGameCreate/mythos-encounter pull request #16
Opened 2024-04-21 12:48 UTC by tibigamePoppo

## 概要

各作業をIngameシーンに統合
## 変更点

 - Ingameシーンに各シーンの変更内容の適応
 - Ingame_Managerのシーンの削除
## テスト

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

2024-04-22 09:56 UTC, Tyunousause requested changes
InGameシーンをビルドして起動すると地面に埋まった状態でスタートする。（歩くと治る）

2024-04-22 13:56 UTC, IwamotoHinata submitted a review, later dismissed
何回か試しましたが、地面に埋まっている...というのは確認できませんでした。
Playerのスポーン場所を取得する機能とかがPlayerSpawnerに実装されていないので、そこはまた修正しておきます

2024-04-22 22:49 UTC, tibigamePoppo commented
@Tyunousause @IwamotoHinata 
ビルドし、ゲーム実行時にy座標0でカメラが呼吸の動きをしていたため、CameraMoveのStartにChangeViewPoint(0)の初期値を入れることで対応しました。

2024-04-25 08:52 UTC, Tyunousause approved these changes
無事に埋まらずにスポーンしました

2024-04-25 08:52 UTC, Tyunousause approved these changes

2024-04-25 08:53 UTC, Tyunousause approved these changes

2024-04-25 12:49 UTC, merged