StageTile
InnovaGameCreate/mythos-encounter pull request #161
Opened 2024-08-23 00:22 UTC by KaPiBaR-001

## 概要

- ステージマネージャー
    - 温度の管理
        - ステージ全体の基準の温度を15~25の間で決定
- 温度
    - ステージに設定されている基準の温度を参照に±3度。
    - もし、設定温度より高くなった場合は２分かけて、設定温度まで戻す
    - 温度を外部から変更可能にする
    - 温度を外部から参照可能にする
- 放射線濃度(msv)
    - 通常のｍsv
        - 通常は90~100msvをランダムに変化。
    - もし、100msvより高くなった場合は毎秒１ずつ変化して、100msvまで戻す
    - msvを外部から変更可能にする
    - msvを外部から参照可能にする

## 変更点

## テスト
 
 動作確認用シーン：

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [x] ビルドが成功するかの確認
## 問題

2024-08-23 13:38 UTC, tibigamePoppo approved these changes
スクリプトを見た限り問題なさそう。

2024-08-25 09:13 UTC, Tyunousause requested changes
テストするシーンにスクリプトは配置しておいてください

2024-08-27 02:04 UTC, KaPiBaR-001 commented
スクリプトをAddComponentしたオブジェクトを追加しました.すいません

2024-08-27 06:56 UTC, Tyunousause requested changes

2024-08-27 12:07 UTC, KaPiBaR-001 commented on Assets/Scripts/Scenes/InGame/Stage/StageTile.cs
> +        }
_temperatureなどの温度に関する関する変数をfloat型に変更し, Mathf.Lerpを用いて目標値に近づかるように変更しました

2024-08-27 12:36 UTC, KaPiBaR-001 commented on Assets/Scripts/Scenes/InGame/Stage/StageTile.cs
> +                    _keep = _temperature;
_keepは設定温度より高くなった場合に用いる変数です.
この時の設定温度はステージ全体の基準温度ではなく,ステージに設定されている温度の±3のどこかなので温度が±3されるたびに書き換えています

2024-08-29 14:45 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Stage/StageTile.cs
> +        }
問題なく温度が変わっていくことを確認しました

2024-08-29 15:47 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Stage/StageTile.cs
> +                    _keep = _temperature;
> 返答ありがとうございます。ステージの設定温度はStageManagerのStandardtemperatureであっていますでしょうか？もしそうでありましたら ![スクリーンショット (1580)](https://private-user-images.githubusercontent.com/73172785/362747210-9231fdf5-554b-4c6e-affc-382d8efe255d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDY0NTcsIm5iZiI6MTcyNDk0NjE1NywicGF0aCI6Ii83MzE3Mjc4NS8zNjI3NDcyMTAtOTIzMWZkZjUtNTU0Yi00YzZlLWFmZmMtMzgyZDhlZmUyNTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE1NDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZGQwYzcxNmU0MTcwY2ZjZDMxOTdhN2QyZDBmZTQ0MWFhN2ZmNTRjYTFlODUwNmM4MzcyNzk2ZWY3OThlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K2jXbvUIfxCcZADCvreDFkH5hH7vCAFNIQpP3b0-_5o) ![スクリーンショット (1581)](https://private-user-images.githubusercontent.com/73172785/362747260-cea9a032-eab3-4f16-a37e-2419b9429f5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDY0NTcsIm5iZiI6MTcyNDk0NjE1NywicGF0aCI6Ii83MzE3Mjc4NS8zNjI3NDcyNjAtY2VhOWEwMzItZWFiMy00ZjE2LWEzN2UtMjQxOWI5NDI5ZjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE1NDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YjUzMzQ1NTNlOGVlMjVhNmY5NWE5YmE4ODdkOWM5NjVhYjk5ZjQyNzlmMGE1YmRmZWRlZmUwYTI5ZjYxZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jJOeAatTv0s5XIVXCbed3nR6qFa794n0qHIa55_bfMc) 温度が設定温度より4°低くなった瞬間がありますので修正をお願いしたいです。

温度は基準の±3度なので、最大6度の差が出ます。
例.基準が15の場合、最大18,最小12なので4度の変化は起こるかも。

2024-08-29 15:59 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Stage/StageTile.cs
> +                    _keep = _temperature;
@KaPiBaR-001  が意図した動きはStageManagerのStandardtemperatureは最初の温度の初期値決定でしかなくて、気温は常にソースコードに直接書かれた_minと_maxで揺れ動くという事であっていますか?

2024-08-29 16:12 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Stage/StageTile.cs
> +                    _keep = _temperature;
@tibigamePoppo 使用書見てきたんだけど気温変化はの平常時は20~25度を揺れ動くであっていますでしょうか？何か変更はありましたか？

2024-08-29 16:45 UTC, KaPiBaR-001 commented on Assets/Scripts/Scenes/InGame/Stage/StageTile.cs
> +                    _keep = _temperature;
@Tyunousause そのつもりでしたがtibgamePoppoさんの例を見ると基準値によって_min,_maxが変わっていたので修正したいと思います

2024-09-02 13:04 UTC, Tyunousause approved these changes

2024-09-02 13:04 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Stage/StageTile.cs
> +                    _keep = _temperature;
@KaPiBaR-001 大丈夫らしいので仕様について確認取ったところオッケーらしいです

2024-09-02 13:05 UTC, merged