痕跡の基礎部分の作成
InnovaGameCreate/mythos-encounter pull request #162
Opened 2024-08-23 08:45 UTC by tibigamePoppo

## 概要

痕跡の基礎を作成
オブジェクトはResources/Prefab/Enemy/TraceFeature
スクリプトはIngame/Enemy/Trace
## 変更点

- 仮置きの音声の追加（唸り声）
- [痕跡]物への干渉の作成
- [痕跡]唸り声の作成
- [痕跡]呼吸音の作成（音声は唸り声で代用中）
- 生成するマネージャーの作成

## テスト
 
 動作確認用シーン：Ingame
テストする際はPrefabのTraceFeatureManagerをシーンの置いてください

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-08-27 07:55 UTC, Tyunousause approved these changes
物への干渉ができません。
インタラクタブルインターフェースへのアクセスには成功していますが、その先の動作にはマウス右クリックの押し下げ入力が必要なので（例えばStageDoor.csであれば2行目）奇跡的なタイミング以外での動作は起きません。
またインタラクタブルインターフェースであれば何にでも反応するので敵がEscapePointにインタラクトして儀式をしようとします

2024-08-27 07:56 UTC, Tyunousause requested changes
物への干渉ができません。
インタラクタブルインターフェースへのアクセスには成功していますが、その先の動作にはマウス右クリックの押し下げ入力が必要なので（例えばStageDoor.csであれば2行目）奇跡的なタイミング以外での動作は起きません。
またインタラクタブルインターフェースであれば何にでも反応するので敵がEscapePointにインタラクトして儀式をしようとします

2024-08-27 14:16 UTC, tibigamePoppo commented
> c553fad
修正しました
特定条件下用のバイパスをインターフェイスに設ける形で修正しました
[c553fad](https://github.com/InnovaGameCreate/mythos-encounter/pull/162/commits/c553fad21b74c694c05d84968fb7f983cb4c3f4d)

2024-08-27 14:17 UTC, tibigamePoppo commented
> 物への干渉ができません。 インタラクタブルインターフェースへのアクセスには成功していますが、その先の動作にはマウス右クリックの押し下げ入力が必要なので（例えばStageDoor.csであれば2行目）奇跡的なタイミング以外での動作は起きません。 またインタラクタブルインターフェースであれば何にでも反応するので敵がEscapePointにインタラクトして儀式をしようとします

https://github.com/InnovaGameCreate/mythos-encounter/commit/c553fad21b74c694c05d84968fb7f983cb4c3f4d
修正しました
特定条件下用のバイパスをインターフェイスに設ける形で修正しました

2024-08-29 15:07 UTC, Tyunousause requested changes
ドアが止まってはいけない位置に止まるのを直してほいいです

2024-08-29 15:07 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Stage/StageDoor.cs
> +            if ((Input.GetMouseButtonDown(1) && _isAnimation == false) || processWithConditionalBypass)
processWithConditionalBypassがtrueの時も_isAnimationがfaleであること御確認してほしいです。多重に開け閉めの命令を受け付けることとなりドアが止まってはいけない位置で止まります。

2024-08-29 16:40 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Stage/StageDoor.cs
> +            if ((Input.GetMouseButtonDown(1) && _isAnimation == false) || processWithConditionalBypass)
[条件式の修正](https://github.com/InnovaGameCreate/mythos-encounter/pull/162/commits/4c9710c9efd50c9ef68f75e51cfb25c4c30ab717)
修正しやした

2024-09-05 17:24 UTC, IwamotoHinata approved these changes
唸り声などの確認ができました

2024-09-05 17:24 UTC, merged