プレイヤー情報をMySQLにアップロードする機能の実装
InnovaGameCreate/mythos-encounter pull request #166
Opened 2024-08-23 12:57 UTC by tibigamePoppo

## 概要

プレイヤー情報をMySQLにアップロードする機能の実装
## 変更点

 - FTPにINSETとUPDATEの機能追加
 - テスト用環境の構築
 - Updateする機能の追加
## テスト
 
 動作確認用シーン：APIDevelop
![image](https://github.com/user-attachments/assets/3ded4409-6aff-4cb8-937a-c873c3cd8915)

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-08-29 15:37 UTC, Tyunousause requested changes
APITestのInspectorにあるAPITesterの_NameInputと_IdInputが抜けている

2024-08-29 15:37 UTC, Tyunousause commented on Assets/Scripts/Data/APITester.cs
> +        if (_NameIput == null || _IdInput == null)
Inspectorに_NameInputまたは_IdInputがセットされているかどうかでのみ判定しているので入力していない場合でも警告が出ない

2024-09-03 02:56 UTC, tibigamePoppo commented on Assets/Scripts/Data/APITester.cs
> +        if (_NameIput == null || _IdInput == null)
修正しました
[74e61c4](https://github.com/InnovaGameCreate/mythos-encounter/pull/166/commits/74e61c4448eb7503c9247f68330d35dab1f304f6)

2024-09-05 17:59 UTC, IwamotoHinata approved these changes
データが送信できることを確認

2024-09-05 19:11 UTC, Tyunousause approved these changes
正常動作を確認

2024-09-05 19:12 UTC, merged