ライトと影の改善
InnovaGameCreate/mythos-encounter pull request #175
Opened 2024-09-06 08:13 UTC by Hiraki-Shunsuke

## 概要
Lightの調整
影の描画についての簡易な軽量化

## 変更点
- Lightの範囲調整
- 各部屋に電気のスイッチを追加
- ShadowCastersの低減
 - 光源のModeをすべてBakedに変更
 - 一部オブジェクトをStaticに変更し事前にベイク
 - Map用CubeのCastShadowをOffに変更

## テスト
 動作確認用シーン：InGame
 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題
- 影の軽量化については簡易なことしかしていない
- 動的にステージを生成しているため事前に床や壁のBakeができないという問題を抱えている。
- 視界範囲に応じた影の描画についてLODを使って対応するのが現実的かも（めちゃくちゃ手間かかる）

2024-09-07 05:55 UTC, tibigamePoppo approved these changes

2024-09-09 07:48 UTC, Tyunousause requested changes
炎の揺らめきと電気が消せることを確認しました。
Unityを閉じるだけでAssets\Plugins\Horror_House\VFX\Candle_Flame.matの変更が作業ツリーに加わるのですがこれ何とかなりませんか？

2024-09-10 02:10 UTC, Hiraki-Shunsuke commented
僕の環境ではそれ発生してないですね
ただ何個か推測は立てているので確認してみます

2024-09-10 08:53 UTC, Tyunousause commented
@Hiraki-Shunsuke ありがとう！そしてすみません、きちんと再度調べたらこのブランチからではなくdevelopでも発生していましたorz
このブランチ自体特有の問題ではないためマージしてしまおうと思うのですが、今この状態でマージした場合、修正途中などの理由で不都合は発生するでしょうか？

2024-09-12 13:01 UTC, Hiraki-Shunsuke commented
@Tyunousause 返信遅くなってすみません
了解しました。あと数個だけRenderingの設定をいじっておきたいPrefabがあるのであと1コミットだけ待ってください！
完了したらここでメンションして連絡します。

2024-09-13 12:22 UTC, Hiraki-Shunsuke commented
@Tyunousause コミットPushしました！マージしていただいても大丈夫です

2024-09-15 05:32 UTC, Tyunousause approved these changes
エラーなどなし

2024-09-15 05:33 UTC, merged