サポートアイテム[餌]実装
InnovaGameCreate/mythos-encounter pull request #182
Opened 2024-09-12 16:44 UTC by nishimura765

## 概要

サポートアイテムの餌を実装しました
## 変更点

変更点1 ドロップアイテム用のTrapFoodPrefabと実際に設置するUsingTrapFoodPrefabを追加
変更点2 UI用のスプライトを追加
変更点3 playerItem.csを一部編集
## テスト
 
 動作確認用シーン：Ingame

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-09-17 08:56 UTC, Tyunousause requested changes
TrapFoodにカーソルを合わせた時に表示されるテキストがbandageであり、アイテム取得後に表示されるアイコンもbandageである

2024-09-17 15:06 UTC, tibigamePoppo requested changes

2024-09-17 15:06 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/TrapFoodEffect.cs
> +                        Destroy(_createdTrapFood);
非常の際にDestroy、表示の際にInstantiateを行っていますが、処理が重たいため、一度生成したものはSetActiveを使って、オブジェクト自体は使いまわしてください。

2024-09-21 21:08 UTC, nishimura765 commented
ご指摘を受けた部分と追加で確認した不具合部分を修正しました。遅れてしまい申し訳ありません。
以下主な変更点です。
・アイコンが正しく表示されるようItemDataを修正
・Enemy.prefabについているコライダー用のオブジェクトのタグをdefaultからEnemyColliderに変更
・TrapFoodEffect.csにあった一部処理をPlayerItem.csに移動
・SetActiveを使ってUsingTrapFoodの表示を切り替えるように処理を変更

2024-09-23 09:20 UTC, tibigamePoppo approved these changes

2024-09-27 15:25 UTC, Tyunousause requested changes
機能面では問題なく作動しました！
ただプレハブをいじったりTagを増設せずとも実装できそうですのでそのように実装してほしいです。

2024-09-27 15:25 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Player/Item/TrapFood/TrapFoodSensor.cs
> +        if (collider.CompareTag("EnemyCollider"))
collider.transform.root.gameobjectで一番上の親オブジェクトが取得できるので
TryGetComponentでEnemyStatusがアタッチされているかどうかを確認するなどの方法で実装していただけますとこれからEnemyの種類が増えた時などでも実装しやすいのでありがたいです。

2024-09-29 02:19 UTC, nishimura765 commented
ご指摘くださった部分を修正いたしました。

2024-10-02 07:19 UTC, Tyunousause approved these changes
コンフリクトが修正されていることを確認しました！

2024-10-02 07:19 UTC, merged