Enemy関連のリファクタリング
InnovaGameCreate/mythos-encounter pull request #187
Opened 2024-09-13 09:26 UTC by Tyunousause

## 概要

大規模なリファクタリングです

## 変更点

 - 敵のスペック情報はすべてEnemyStatusに集約されました
 - 敵の情報のうちいくつものスクリプトをまたいでいるものをEnemyStatusに集約しました。
 - 仕様から消えた変数をいスクリプトの中にハードコード（視界の長さ）
 - 未使用になっていた変数を削除
 - 未使用になっていた関数を削除
 - 変数名の間違いを削除
 - デバッグ時にマップ上に書き込まれる光が実際に届く距離を無視して無限に届くものとして描画されていたのを修正
 - プレハブが一部壊れているのを修正
 - Bindのデバフと水のデバフが同時に食らったとき、一時的に（1s以下）片方のデバフしか反映されないことを修正
 - スタミナ切れデバフ硬直、Stateの変更による速度変化が1s待つことなくすぐに反映されるように修正

## テスト
 
 動作確認用シーン：Ingame_Enemy Test

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-09-13 12:50 UTC, tibigamePoppo requested changes
動作確認自体はエラー等はなかったです。気になった部分だけコメントしました

2024-09-13 12:50 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/EnemyMove.cs
> +                                }
/
```suggestion
                                //スタミナを削れるなら、これがあるのはスタミナが0のキャラがいた時にまともに動かすため
                                    _enemyStatus.StaminaChange(_enemyStatus.Stamina - 1);

```
上のif文で0 >= _enemyStatus.Staminaがあり、elseでここに入ってるのこのif (0 < _enemyStatus.Stamina)いらないと思う。

2024-09-15 14:19 UTC, tibigamePoppo approved these changes
OK!

2024-09-20 13:42 UTC, IwamotoHinata approved these changes
動作確認問題なしです

2024-09-20 13:42 UTC, merged