プレイヤーのマルチプレイ周りの実装
InnovaGameCreate/mythos-encounter pull request #190
Opened 2024-09-14 09:41 UTC by s4r6

アニメーションの変更、プレイヤーの移動、アニメーションの同期それに伴ったSimpleKCCの導入

## 概要

・プレイヤーの移動、アニメーションの同期  
・SimpleKCCの導入

## 変更点

・アニメーターの変更

## テスト
 
 動作確認用シーン：MultiPlayer_SpawnTest

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [x] ビルドが成功するかの確認
## 問題

2024-09-15 14:20 UTC, tibigamePoppo approved these changes

2024-09-20 05:21 UTC, Tyunousause approved these changes
プレイヤーcharacterが意図しない方向へ移動し続ける

2024-09-20 05:22 UTC, Tyunousause requested changes
プレイヤーcharacterが意図しない方向へ移動し続ける/再現性はあったりなかったり

2024-09-27 16:15 UTC, IwamotoHinata approved these changes
問題なく動作してました

2024-10-01 04:08 UTC, Hiraki-Shunsuke commented
@Tyunousause 
オンライン実装の進行にこの問題の解決が必要です。
要因や具体的な発生条件が不明であるため、実装に大きな問題などなければそのままマージを許可していただきたいのですが、このまま通すことで考えられる重大な問題などはありますか？

2024-10-01 07:37 UTC, Tyunousause approved these changes
かならず起こらないことであるかつ重要事項なので特別にマージしてよいといわれたのでOKだします

2024-10-02 12:43 UTC, tibigamePoppo commented
コンフリクトがあってマージできないため、修正をお願いします！

2024-10-03 00:27 UTC, merged