温度計実装
InnovaGameCreate/mythos-encounter pull request #196
Opened 2024-09-22 02:33 UTC by nishimura765

## 概要

サポートアイテムの温度計を実装しました。
## 変更点

変更点1 Thermometer.prefabとUsingThermometer.prefab、それらに関係するスクリプトを追加
変更点2 PlayerItemスクリプトに温度計に関係する処理を追加
変更点3 StageTileスクリプトを紐づけたFloor.prefabをテストシーンように追加
## テスト
 
 動作確認用シーン：Ingame_ThermometerTest

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-09-23 09:21 UTC, tibigamePoppo approved these changes
コードを見た限り特に気になる点はありませんでした

2024-09-27 14:37 UTC, Tyunousause requested changes
温度計を左クリックで使用し3秒待って温度が表示される前にアイテムスロットを変更すると温度計が二度と使えなくなる

2024-09-27 14:45 UTC, IwamotoHinata requested changes
![スクリーンショット 2024-09-27 232230](https://github.com/user-attachments/assets/2bbdcf4e-edeb-4865-ab3b-21005c4fdbe6)
PlayerSpawnerのスクリプトの中身が消えています。再度設定をお願いします

2024-09-27 14:45 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/Thermometer/ThermometerMove.cs
> +
```suggestion
private void OnDisable()
{
    _playerItem.ChangeCanUseItem(true);//　アイテムを使用できるようにする
}
```
この関数を追加してあげてください。
現状、温度計使用中にスロットを変更させるとアイテムが二度と使えなくなってしまいます。
そこで、UsingThermometer（ゲームオブジェクト）が非表示になった際にアイテムを使用できるようにすると解決できます

2024-09-29 02:35 UTC, nishimura765 commented
ご指摘を受けた部分を修正いたしました。

2024-10-02 07:46 UTC, Tyunousause approved these changes
プレイヤースポナーのInspectorの抜けが修正されていません

2024-10-02 07:47 UTC, Tyunousause requested changes
プレイヤースポナーのInspectorの抜けが修正されていません

2024-10-03 00:56 UTC, nishimura765 commented
> プレイヤースポナー

2024-10-03 19:47 UTC, Tyunousause approved these changes
問題なく修正されているのを確認しました。
作業ブランチ間違えてすまない

2024-10-04 00:13 UTC, merged