放射線測定器実装
InnovaGameCreate/mythos-encounter pull request #202
Opened 2024-10-01 12:26 UTC by nishimura765

## 概要

サポートアイテムの放射線測定器を実装しました。
## 変更点

変更点1 geigerCounter.prefabとusingGeigerCounter.prefabを追加
変更点2 PlayerItem.csを編集

## テスト
 
Ingame_ThermometerTest
 動作確認用シーン：

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-10-03 01:14 UTC, tibigamePoppo requested changes

2024-10-03 01:14 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
> +        [SerializeField] private GameObject _thermometer;//Camera�ɕt�����Ă��鉷�x�v
``` suggestion
[SerializeField] private ThermometerMove _thermometer;//Cameraに付属している温度計
``` 
こちらでクラスを設定しておけば関数を呼び出すたびにGetComponentする必要がなくなります

2024-10-03 04:59 UTC, nishimura765 commented on Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
> +        [SerializeField] private GameObject _thermometer;//Camera�ɕt�����Ă��鉷�x�v
先ほどGetComponentで実行している関数をまとめて修正しました。SetActiveを使って表示切替しているアイテムだけGameObject変数が必要なので残しています。

2024-10-03 07:50 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
> +        [SerializeField] private GameObject _thermometer;//Camera�ɕt�����Ă��鉷�x�v
その場合は_thermometer.gameobject.SetActiveのようにすれば動くと思います

2024-10-03 08:04 UTC, nishimura765 commented on Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
> +        [SerializeField] private GameObject _thermometer;//Camera�ɕt�����Ă��鉷�x�v
了解です。クラスだけ残すよう再度修正しておきます。

2024-10-04 00:13 UTC, tibigamePoppo approved these changes
特に気になるところはないですが、コンフリクトしているのでrebaseだけしておいてください

2024-10-08 14:32 UTC, IwamotoHinata approved these changes
動いている様子は確認できました。

2024-10-08 14:32 UTC, merged