痕跡（気温変化,汚染）
InnovaGameCreate/mythos-encounter pull request #205
Opened 2024-10-02 14:32 UTC by KaPiBaR-001

## 概要

## 変更点

## テスト
 
 動作確認用シーン：

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [x] ビルドが成功するかの確認
## 問題

2024-10-02 15:06 UTC, KaPiBaR-001 commented
変更点1 FeatureView に機能の追加
変更点2 TemperatureFeatureに機能の追加
変更点3 RadiationFeatureに機能の追加

テストシーン　Ingame_Stage_Tile Test

問題点 Ignorで始めたときPlayerItemでエラーが起きていたのでテストはできていません

2024-10-03 02:17 UTC, tibigamePoppo requested changes

2024-10-03 02:17 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +        public ReactiveProperty<GameObject> TemperatureTrace = new ReactiveProperty<GameObject>();
```suggestion
        private ReactiveProperty<GameObject> TemperatureTrace = new ReactiveProperty<GameObject>();
        public IObservable<GameObject> OnTemperatureTrace { get => TemperatureTrace ; }
```
値を直接他のクラスから触れるのはまずいので、カプセル化してほしいです

2024-10-03 02:17 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +        public StageTile stagetile;
```suggestion
        private StageTile _stagetile;
        public StageTile stagetile { get { return _stagetile; } }
```
値を直接他のクラスから触れるのはまずいので、カプセル化してほしいです

2024-10-03 02:17 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +                if (Physics.Raycast(ray, out hit))
Raycastの場合、rayを飛ばした最初のオブジェクトを取得します。現状は最初にrayに当たるのはStageタイルを持ったオブジェクトではないので、rayを飛ばして配列で取得する必要があります。そのためRaycastAllを使って、foreach使い、取得した配列について処理してください

2024-10-03 02:17 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/RadiationFeature.cs
>  using System.Threading;
```suggestion
using System;
using Cysharp.Threading.Tasks;
using System.Threading;
using UniRx;
```
これがないとイベントが動きません

2024-10-03 02:17 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/RadiationFeature.cs
> +            });
```suggestion
            _view.OnTemperatureTrace
                .Skip(1)
                .Subscribe(_ =>
                {
                    _change = _view.stagetile.Msv + 10;
                    if (_change < 200)
                    {
                        _change = 200;
                    }
                    _view.Msv(_change);
                }).AddTo(view.gameObject);
```
Skipを入れないと、一番最初に何も入っていない状態でイベントが発行されエラーが置きます。
またAddToに関しては、このクラス自体がUnityにないためviewが破棄されたタイミングで破棄するようにすると、実装できました

2024-10-03 02:17 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/TemperatureFeature.cs
> +using UnityEngine.Rendering.HighDefinition;
```suggestion
using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using UnityEngine.Rendering.HighDefinition;
using UniRx;
```
説明省略

2024-10-03 02:17 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/TemperatureFeature.cs
> +
```suggestion
            _view.OnTemperatureTrace
                .Skip(1)
                .Subscribe(_ =>
                {
                    _change = _view.stagetile.Temperature - 10;
                    _view.Temperature(_change);
                }).AddTo(view.gameObject);
            
```
説明省略

2024-10-03 02:17 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Stage/StageTileTest.cs
> +        private float _Test;
```suggestion
        private float _test;
```
細かいですが_の次は小文字です。また機能が完成しているなら、変数名をtestから適切なものに変えてほしいです

2024-10-03 02:17 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +        public ReactiveProperty<GameObject> TemperatureTrace = new ReactiveProperty<GameObject>();
```suggestion
        public ReactiveProperty<GameObject> floor = new ReactiveProperty<GameObject>();
```
TemperatureTrace という変数名ですが、中身がGameObjectであり、RadiationFeatureがこの変数を参照しているのに違和感があります。適切な名前に変えてほしいです。

2024-10-04 06:00 UTC, KaPiBaR-001 commented on Assets/Scripts/Scenes/InGame/Stage/StageTileTest.cs
> +        private float _Test;
動作確認するためだけのスクリプトだったので削除しておきます

2024-10-04 06:31 UTC, KaPiBaR-001 commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +                if (Physics.Raycast(ray, out hit))
Raycastの第5引数でレイヤマスクの設定をしての実装でも大丈夫でしょうか

2024-10-04 07:07 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +                if (Physics.Raycast(ray, out hit))
それでも大丈夫です。

2024-10-04 08:44 UTC, KaPiBaR-001 commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +                if (Physics.Raycast(ray, out hit))
了解しました
現在出している修正でRaycastの第5引数でレイヤマスクの設定をしての実装はできていると思います

2024-10-04 12:55 UTC, tibigamePoppo approved these changes

2024-10-04 12:57 UTC, tibigamePoppo commented
コードを見た限り気になる点はなかったです

2024-10-04 13:22 UTC, tibigamePoppo requested changes

2024-10-04 13:22 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +                if (hit.collider.layerOverridePriority == 7)
```suggestion
                if (hit.collider.layerOverridePriority == 7)
```
hit.colliderがずっとnullになってエラーが起こります。
動作確認ですが、safemodeで入る場合は問題の個所をコメントアウトすれば動作するので、その方法で正常に動作するかを確認してみて下さい

2024-10-07 02:24 UTC, KaPiBaR-001 commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +                if (hit.collider.layerOverridePriority == 7)
修正しました
ご確認お願いします

2024-10-09 00:42 UTC, tibigamePoppo requested changes
ちなみにですが、動作確認の際にDebugLogを入れてみて確認しても反応がなかったのですが、そちらの環境では動作確認はできていますか？

2024-10-09 00:42 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +        public StageTile stagetile { get { return _stagetile; } }
```suggestion
        private ReactiveProperty<StageTile> floor = new ReactiveProperty<StageTile>();
        public IObservable<StageTile> OnFloor { get => floor; }
        private Vector3 direction = new Vector3(0, -1, 0);
```
今思えばGameObjectにする必要がないので、クラスのまま渡していい気がしました

2024-10-09 00:42 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +                    floor.Value = _floor;
```suggestion
                    _floor = hit.collider.gameObject;
                    floor.Value = _floor.GetComponent<StageTile>();
```

2024-10-09 00:42 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/RadiationFeature.cs
> +            }).AddTo(view.gameObject); ;
```suggestion
            _view.OnFloor.Skip(1).Subscribe(tile =>
            {
                _change = tile .Msv + 10;
                if (_change < 200)
                    _change = 200;
                _view.Msv(_change);
            }).AddTo(view.gameObject); ;
```

2024-10-09 00:42 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/TemperatureFeature.cs
> +            }).AddTo(view.gameObject); ;
```suggestion
            _view.OnFloor.Skip(1).Subscribe(tile  =>
            {
                _change = tile .Temperature - 10;
                if (_change < tile .Keep - 10)
                    _change = tile .Keep;
                _view.Temperature(_change);
            }).AddTo(view.gameObject); ;
```

2024-10-09 00:42 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +            stagetile.MsvChange(change);
```suggestion
            floor.Value.MsvChange(change);
```

2024-10-09 00:42 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
> +            Debug.Log(stagetile.Temperature);
```suggestion
            floor.Value.TemperatureChange(change);
            Debug.Log(floor.Value.Temperature);
```

2024-10-10 10:51 UTC, tibigamePoppo approved these changes

2024-10-11 18:32 UTC, IwamotoHinata reviewed
![スクリーンショット 2024-10-12 033023](https://github.com/user-attachments/assets/6b0d9eab-92f5-4d58-8519-978004912dae)

痕跡に関する変更だったので敵が出現するIngameシーンで確かめてみました。
TraceFeatureManagerのDeugTypeに気温変化, 汚染の要素を入れたところNullReferenceになりました。

2024-10-11 19:37 UTC, tibigamePoppo commented
デバック方法について
SceneにTraceFeatureManagerとStageManagerを入れれば動くはず！

2024-10-12 14:10 UTC, merged