SAN値回復薬実装
InnovaGameCreate/mythos-encounter pull request #207
Opened 2024-10-03 05:12 UTC by nishimura765

## 概要

サポートアイテムのSAN値回復薬を実装しました。アイテムIDは28にしています。
使用すると0.5秒ごとにSAN値が1回復し,5秒経過で最大10回復するようになっています。
仕様が間違っていれば修正しますので教えてください。

## 変更点

変更点1 SanityPotion.Prefabを追加 

## テスト
 
 動作確認用シーン：Ingame

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-10-03 07:57 UTC, tibigamePoppo requested changes

2024-10-03 07:57 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/SanityPotionEffect.cs
> +                }
```suggestion
                yield return new WaitForSeconds(0.5f);
                    ownerPlayerStatus.ChangeSanValue(1, ChangeValueMode.Heal);
```
おそらく0.5秒まつといった処理だと思いますが、この場合はWaitForSecondsを使って指定秒数待つ方がわかりやすいと思います。また、10回だけを数える場合は発動回数をカウントするintを作ってそれが10になったタイミングで処理を止めれば良いと思います

2024-10-03 07:57 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/SanityPotionEffect.cs
> +                if (Time.time - _startTime >= 5.0f || ownerPlayerStatus.nowPlayerSanValue == 100)
```suggestion
                if (Time.time - _startTime >= 5.0f || ownerPlayerStatus.nowPlayerSanValue => 100)
```
一応、処理を100以上で止めるようにしておいた方が、想定外の挙動には強くなると思います

2024-10-03 07:57 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/SanityPotionEffect.cs
> +
```suggestion
```
細かいですがいらない余白は詰めておくと全体の行数が短くなって見やすいです

2024-10-03 07:57 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/SanityPotionEffect.cs
> +
```suggestion
```
開発で確認のために必要だったのだと思いますが、動作確認では必要ないと思うので消して欲しいです

2024-10-04 12:43 UTC, nishimura765 commented
ご指摘を受けた部分を修正しました。

2024-10-04 12:55 UTC, tibigamePoppo reviewed
コードを見た限り気になる点はなかったです

2024-10-04 12:55 UTC, tibigamePoppo approved these changes

2024-10-05 14:25 UTC, IwamotoHinata approved these changes
回復するの確認しました

2024-10-05 14:25 UTC, merged