触手のアイテムの追加
InnovaGameCreate/mythos-encounter pull request #214
Opened 2024-10-04 16:47 UTC by tibigamePoppo

## 概要

触手のアイテムの追加
## 変更点

- 触手のアイテムの追加
- スタミナに関するバフの処理の修正
- アドレナリン注射器の修正

## テスト
 
 動作確認用シーン：Ingame
PrefabにあるTantacleをステージにおいてテストしてください
触手の仕様：https://www.notion.so/tokushima-igc/5534abfcea44439ba4cf184f77cc3153?pvs=4

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-10-08 15:23 UTC, IwamotoHinata requested changes
![スクリーンショット 2024-10-09 001818](https://github.com/user-attachments/assets/e355d440-c7f6-462b-98dc-c2d3a370c158)

写真のPrefabのところを「Tentacle Variant.prefab」に変更してください。エラーが出てます。

後、触手の効果を記述したスクリプト「Tentacle.cs」ですが「TentacleEffect.cs」に変更をお願いします。

2024-10-09 00:21 UTC, tibigamePoppo commented
> ![スクリーンショット 2024-10-09 001818](https://private-user-images.githubusercontent.com/86921212/374621380-e355d440-c7f6-462b-98dc-c2d3a370c158.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzMxOTAsIm5iZiI6MTcyODQzMjg5MCwicGF0aCI6Ii84NjkyMTIxMi8zNzQ2MjEzODAtZTM1NWQ0NDAtYzdmNi00NjJiLTk4ZGMtYzJkM2EzNzBjMTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAwMTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1OGQwNmFkYTI1NjQ3YjUxOGI4ZWM5ZTI4MzMyMmFhYzZjMGQ2NTYxOTk4MWQxMjJlZGZjMzAzNTE0MjIwNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KVDE7-cqTIQfpV2_GqtttKMvADoCxX3tm37LnuVncg8)
> 
> 写真のPrefabのところを「Tentacle Variant.prefab」に変更してください。エラーが出てます。
> 
> 後、触手の効果を記述したスクリプト「Tentacle.cs」ですが「TentacleEffect.cs」に変更をお願いします。

修正しました
[3cd3a99](https://github.com/InnovaGameCreate/mythos-encounter/pull/214/commits/3cd3a99a2c5138b3986176f89fec0df2218ffa5f)

2024-10-09 09:11 UTC, IwamotoHinata approved these changes
大丈夫でした！

2024-10-11 18:18 UTC, Tyunousause approved these changes
大変結構！

2024-10-11 18:18 UTC, merged