Feature/UI/title
InnovaGameCreate/mythos-encounter pull request #215
Opened 2024-10-04 22:18 UTC by twink-star

## 概要

タイトル画面の実装

## 変更点

- TitleUI.csの追加
- TitleState.csの追加
- TitleUIの追加と配置
## テスト
 
 動作確認用シーン：Title

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [x] ビルドが成功するかの確認
## 問題

2024-10-05 04:55 UTC, tibigamePoppo requested changes
修正点が多きく個別でコードから修正することが難しいため、こちらでまとめて書かせていただきます。

UIに関してはMVPパターンに従い設計してください。
今回の場合、Viewは各ボタンにマウスカーソルが乗った時と押された時にイベントを発行する関数を作り、Presenterはそれらすべてをsubscribeし、適切に表示切り替える行う形にしてください。

2024-11-06 06:01 UTC, tibigamePoppo requested changes

2024-11-07 17:17 UTC, tibigamePoppo commented
canvasの設定を現状だと画面サイズでUIの大きさが変化するため、以下の設定に修正して下しさい。
また、変更するとパネルの大きさも再調整する必要があります。
![image](https://github.com/user-attachments/assets/07e38522-9315-44c1-8feb-040d0411cea7)

2024-11-08 13:04 UTC, tibigamePoppo approved these changes
特に問題はなさそう。動作確認しました。

2024-11-22 09:26 UTC, Tyunousause approved these changes
各主動作問題なく作動していました。

2024-11-22 09:26 UTC, merged