デバッグ用のツール開発
InnovaGameCreate/mythos-encounter pull request #217
Opened 2024-10-05 23:20 UTC by IwamotoHinata

## 概要

デバッグ用のツール開発
## 変更点

- デバッグ用のツールを作成しました。以下にできることを列挙
1. 脱出地点にワープ
2. 脱出アイテムを全て目の前に移動
3. プレイヤーの体力, SAN値をSliderで変更可能
4. アイテムの生成(asset/Resources/Prefab/Itemの中にPrefabファイルを置くと自動でボタンが増えます)

## テスト
 
 動作確認用シーン：Ingame_Player
メニューバーのところに「DebugTool」項目が増えているので、そこを押してCreateGUIを選択してください。
レイアウトとしては以下の写真のように想定しています。
![スクリーンショット 2024-10-06 081043](https://github.com/user-attachments/assets/8d682abd-4952-4cdd-8eb1-fde1e92a77b2)

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-10-06 10:31 UTC, tibigamePoppo approved these changes

2024-10-09 08:24 UTC, Tyunousause requested changes
敵の攻撃を無効化が、チェックボックスのオンオフを一度繰り返さないとできない。（初期状態では無効化するにチェックマークがついているが反映されていない）

2024-10-09 08:24 UTC, Tyunousause commented on Assets/Editor/DebugMenu.cs
> +            .Skip(1)
スキップする必要はなく思える

2024-10-09 08:24 UTC, Tyunousause commented on Assets/Editor/DebugMenu.cs
> +    private ReactiveProperty<bool> _applyDebugValueMode = new ReactiveProperty<bool>(true);
将来的に使用予定がないのであれば現状ReactivePropertyであるべき点がない

2024-10-09 08:56 UTC, IwamotoHinata commented on Assets/Editor/DebugMenu.cs
> +    private ReactiveProperty<bool> _applyDebugValueMode = new ReactiveProperty<bool>(true);
ReactivePropertyを使ってる意図としては、単純にSliderの値が変更されたときにのみ、全てのプレイヤーの値を変更したいと考えたからです。
OnGUI関数で常にSliderの値を全てのプレイヤーに適応させてもいいと思いますが、一連の処理が重くなりそうだったのでReactivePropertyで値の変化を監視してます。どちらの方が良いのでしょうか...？

2024-10-09 08:57 UTC, IwamotoHinata commented on Assets/Editor/DebugMenu.cs
> +            .Skip(1)
確かに要らなかったです...
消しておきます！

2024-10-10 10:53 UTC, tibigamePoppo commented on Assets/Editor/DebugMenu.cs
> +    private ReactiveProperty<bool> _applyDebugValueMode = new ReactiveProperty<bool>(true);
Build後に動作に影響を与えないならどちらでも良いと思う

2024-10-10 21:41 UTC, Tyunousause commented on Assets/Editor/DebugMenu.cs
> +    private ReactiveProperty<bool> _applyDebugValueMode = new ReactiveProperty<bool>(true);
17行目はゴメンみすった岩本君の言うとおりだ。
でも18行目は_applyDebugValueMode.Valueの形でしか使ってないからただのboolの方がいいと思う

2024-10-11 06:08 UTC, IwamotoHinata commented on Assets/Editor/DebugMenu.cs
> +    private ReactiveProperty<bool> _applyDebugValueMode = new ReactiveProperty<bool>(true);
> 17行目はゴメンみすった岩本君の言うとおりだ。 でも18行目は_applyDebugValueMode.Valueの形でしか使ってないからただのboolの方がいいと思う

修正しました

2024-10-11 14:57 UTC, Tyunousause approved these changes

2024-10-11 14:57 UTC, merged