敵のアニメーション修正と実装
InnovaGameCreate/mythos-encounter pull request #241
Opened 2024-10-13 01:05 UTC by Hiraki-Shunsuke

## 概要
敵３種のアニメーションの実装と修正

## 変更点
- 深きもののアニメとテクスチャ変更
- 落とし子のアニメとテクスチャ変更
- ミ＝ゴのアニメ変更

## テスト
 動作確認用シーン：InGame_TestEnemy
 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認

2024-10-17 14:46 UTC, tibigamePoppo approved these changes

2024-10-18 08:28 UTC, IwamotoHinata requested changes
DeepOnes以外問題ありました。

Migoのアニメーション遷移が正常に設定されてなかったです
![スクリーンショット 2024-10-18 170451](https://github.com/user-attachments/assets/88d0d064-2323-4044-894a-6dcf6d61c33f)

SpawnOfCthllhuはAnimatorコンポーネントにアバターが設定されておらず、アニメーションが発生しませんでした。
![スクリーンショット 2024-10-18 172800](https://github.com/user-attachments/assets/471b65b9-f04e-4dc5-a3c0-6d3612a0cb6b)

2024-10-20 09:49 UTC, Hiraki-Shunsuke commented
@IwamotoHinata 修正しました

2024-10-22 17:07 UTC, IwamotoHinata approved these changes
修正していただきありがとうございます！
問題ありませんでした

2024-10-22 17:07 UTC, merged