ユニークアイテムの冠の作成
InnovaGameCreate/mythos-encounter pull request #259
Opened 2024-10-23 01:03 UTC by tibigamePoppo

## 概要

ユニークアイテムの冠の作成
## 変更点

 - ユニークアイテムの冠の作成
 - 似た処理をしているお守りの修正
## テスト
 
 動作確認用シーン：Ingame
1. Ingame起動後、ResourceのItemからCap.prefabを生成する。
2. デバックツール等でゲームをクリアする
3. 獲得しているお金が1.5倍になっている

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-10-23 01:04 UTC, tibigamePoppo commented
以下のプルリクからの派生です。先に以下のプルリクを通してからマージしてください。
https://github.com/InnovaGameCreate/mythos-encounter/pull/252

2024-10-25 10:28 UTC, Tyunousause requested changes
capプレハブの子オブジェクトのCubeにアタッチされているBoxColliderに判定を吸われてcapを拾いにくい
Sanチェックによって冠を失った場合、冠の効果が消滅せずアイテム欄に冠がないのに獲得ゴールドが1.5倍になる（Bodyparalyze.csのOnthrowの呼び出しが行われる行が実行されたとき、アイテムスロットの更新はまだされていないため。アイテムスロットの更新は78行目で行われている）

2024-10-25 12:05 UTC, tibigamePoppo commented
> capプレハブの子オブジェクトのCubeにアタッチされているBoxColliderに判定を吸われてcapを拾いにくい Sanチェックによって冠を失った場合、冠の効果が消滅せずアイテム欄に冠がないのに獲得ゴールドが1.5倍になる（Bodyparalyze.csのOnthrowの呼び出しが行われる行が実行されたとき、アイテムスロットの更新はまだされていないため。アイテムスロットの更新は78行目で行われている）

修正しました
[8db0088](https://github.com/InnovaGameCreate/mythos-encounter/pull/259/commits/8db00884755a8907b3b3648afc2806582fc77553)

2024-10-30 13:06 UTC, Tyunousause approved these changes
問題なく修正されていることを確認しました

2024-11-01 07:16 UTC, merged