包帯の作成
InnovaGameCreate/mythos-encounter pull request #28
Opened 2024-05-01 16:23 UTC by IwamotoHinata

## 概要

包帯を作成しました。
IteEffect(抽象クラス)を改善した。
プレイヤーの視点の可動域を広げ、よりアイテムを入手しやすくした。
アイテムにRigidBogyをつけて、アイテムを投げられるようにした。
## 変更点

- 包帯を作成
- IteEffectを改善。アイテムを拾ったときに拾得者の情報（PlayerStatus）をアイテムに流すようにした。
- アイテム関連の処理を見直しました。ItemSlot（List）の変更をアイテム側で行えるように→好きなタイミングでListを変更可能になりました。
- プレイヤーをより自由かつ自然に操作可能になった。
## テスト

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

2024-05-01 16:45 UTC, tibigamePoppo commented
以前より包帯の仕様が固まったため、こちらで共有します。
https://www.notion.so/tokushima-igc/c48fe5462a734878a6f74a9fdb092a82?pvs=4#ebeb53eeba61493da5640a9cb2765e7f
上記に仕様があります。
下記の機能の実装をお願いします。
1.アイテムを使用すると10秒間包帯を巻くエフェクトを出す（とりあえずエフェクト無視してください）
2.エフェクト中は移動速度が半減になる
3.エフェクト中にダメージを受けると、アイテム使用がキャンセルされる
4.エフェクト後、止血が止まる

2024-05-03 17:46 UTC, IwamotoHinata commented
少しリファクタリングするのでレビューは待ってください

2024-05-04 06:09 UTC, tibigamePoppo requested changes
動作確認ではお問題なかったです。
一部機能だけ変更してほしいです。

2024-05-04 06:09 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
> +        }
```suggestion
        private bool _isUseItem = false;
        public void UseItem(bool use)
        {
            _isUseItem = use;
        }

        /// <summary>
        /// 移動速度を変更させる関数
        /// </summary>
        /// <param name="value">変更量</param>
        public void ChangeSpeed()
        {
            _speed.Value =  (int)( _speedBase * (_isUseItem ? 0.5f : 1));
        }
``` 
移動速度の変更ですが、現状だと複数の移動速度変更の効果があると、お互いに干渉してしまいます。
なので、それぞれ、状態をbool値で管理し、ChangeSpeedではその状態によって _speed.Valueを変化させるのはどうですか。
干渉する例.
①影響１で移動速度が半減して2.5になる（影響終了時は_speedBaseの5に戻る）
②影響２で移動速度が半減して1.25になる（影響終了時は_speedBaseの2.5に戻る）
③影響１が終了して移動速度が5に戻る
④影響２が終了して移動速度が2.5に戻る
⑤以降ずっと2.5のままになる。

2024-05-04 06:09 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/BandageEffect.cs
>              ownerPlayerStatus.ChangeSpeed(ownerPlayerStatus.nowPlayerSpeed / 2);
```suggestion
            ownerPlayerStatus.UseItem(true);
            ownerPlayerStatus.ChangeSpeed();
``` 
別のコメントで書いた修正案の場合の変更箇所
以下while分も同様に変更すると良いと思います（useItemの引数はfalse）

2024-05-04 06:09 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/BandageEffect.cs
> +                    ownerPlayerItem.ThrowItem(ownerPlayerItem.nowIndex);
```suggestion

``` 
アイテム使用に失敗した場合は、アイテムをアイテムスロットに残したままにしてほしいです。

2024-05-04 08:57 UTC, Tyunousause requested changes
原因探していますが、包帯を取って使用すると完全い体が地面に固定されてしまう事があります

2024-05-04 10:39 UTC, IwamotoHinata commented
修正したので再度レビューお願いします。
あと、こちらでも何回か試しましたが体が固定化されることはなかったです…
ただ、床が薄い都合上プレイヤーがアイテムの上に乗っていると、アイテムが床をすり抜けて、奈落に落ちるバグが発生しています。

①床を分厚くする。
②床にアイテムがあるときはRigidBodyのisTriggerをfalseにする。
どちらかの方法で対処しようかな...と今のところ考えています

2024-05-04 10:45 UTC, tibigamePoppo approved these changes
動作確認を行いました。
エラーなどは大丈夫でした。

2024-05-04 15:54 UTC, Tyunousause approved these changes
エラーなど問題なく動作しました。動けなくなることに関しては一戸前のコミットでダッシュと歩きを小刻みに繰り返しながら包帯を使う事で再現できました。一方でこの変更の打とでは再現できなかったのでおそらく橋本の方式で解決したと思われます（でも...走る状況などによる速度変化は包帯による速度変化とは独立してるし...もしかしたら治ってないかも）。

2024-05-04 15:54 UTC, merged