ショットガン実装(修正済)
InnovaGameCreate/mythos-encounter pull request #281
Opened 2024-11-18 08:35 UTC by nishimura765

概要
爆竹ブランチと同様にショットガンブランチでも最新developとマージしており、うまくテストプレイできなかったため一旦マージ前のコミットからプルリクをし直しました。

変更点
変更点1 ショットガン関連のprefab,animation,effect等を追加
変更点2 viatualCameraに揺れを発生させる機能を追加
変更点3 soundManagerに発射音などの音源を追加

テスト
動作確認用シーン：Ingame, Ingame_ShotgunTest
(ヒット時の敵の動作確認はShotgunTestで行っています。シーン再生時、モード選択後にアイテム未実装である_multiPlayer1が湧きますが、アクティブ状態をオフにすることでオフライン用のPlayerに切り替わり、アイテムを使用することができます)

 複雑であったり、わかりにくい部分のコメントアウトでの説明
 命名規則の統一
 変更箇所にエラーが発生してるかの確認
[] ビルドが成功するかの確認
問題
問題点1　弾が壁や床にあたったときに弾痕を発生させる処理が未実装であること
問題点2　playerの視界用ライトがアイテムに当たり、カメラ前にあるショットガンが光ってしまう。
　　　　　(lightLayerを設定することで解決可能)

2024-11-18 13:02 UTC, tibigamePoppo requested changes

2024-11-18 13:02 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemDataBase.cs
> +
```suggestion
```
特に変化のない変更はcommitから外してください。

2024-11-18 13:03 UTC, tibigamePoppo commented
**動作確認メモ**
1. RunnerSpawnerのRunnerPrefabがNoneになっているので、NetworkRunnerを設定する
(NetworkRunnerはResources/Prefab/MultiPlayerのファルダの中にある)
2. PlayerUIのprefabをシーンに追加する

2024-11-18 13:04 UTC, tibigamePoppo commented
ショップ関連の情報のTypeは一応Battleにしておいて欲しいです。
![image](https://github.com/user-attachments/assets/92726935-5f20-4f16-9149-d6befbc5e3f1)

2024-12-05 17:06 UTC, nishimura765 commented
ご指摘いただいた部分を修正しました。
ただShotgun.prefabのAddNetworkObjectについては、こちらの環境だと選択画面が出てきていないので保留しております。

2024-12-15 13:45 UTC, tibigamePoppo approved these changes
コードを見た限りは問題なさそう

2024-12-29 07:59 UTC, tibigamePoppo commented
他のアイテムのコンフリクトを修正する際に必要なので通します

2024-12-29 07:59 UTC, merged