[アイテム]ラーン=テゴスの石像実装
InnovaGameCreate/mythos-encounter pull request #294
Opened 2024-12-06 12:09 UTC by nishimura765

## 概要

ラーン=テゴスの石像アイテムを実装しました。
## 変更点

変更点1　StatueOfRhan.prefabを追加
変更点2　playerItemを編集
## テスト
 
 動作確認用シーン：Ingame,Ingame_ItemTest

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-12-09 13:57 UTC, tibigamePoppo requested changes
PlayerItemで機能実装をしているので可能な限りアイテムの方で機能実装してほしいです。

2024-12-09 13:57 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
> +        }
```suggestion
```
アイテムの効果は可能な限りアイテムエフェクト(StatueOfRhanEffect.cs)の方で実装してほしい

2024-12-09 13:57 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/StatueOfRhanEffect.cs
> +
```suggestion
        public async UniTaskVoid ItemEffect(CancellationToken token)
        {
            while (true)
            {
                for (int i = 0 ; i < 10 ; i++)
                {
                    await UniTask.Delay(TimeSpan.FromSeconds(10));
                    if (token.IsCancellationRequested) break;
                    ownerPlayerStatus.ChangeHealth(1, ChangeValueMode.Heal);
                }
                ownerPlayerStatus.ChangeSanValue(1, ChangeValueMode.Damage);
            }
        }
```
コルーチンよりUniTaskで書いた方が簡単に書けるかも？

2024-12-09 13:57 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/StatueOfRhanEffect.cs
> +        {
```suggestion
        private CancellationTokenSource _cancellationTokenSource = new CancellationTokenSource();
        public override void OnPickUp()
        {
            ItemEffect(_cancellationTokenSource.Token).Forget();
```
もしUniTaskで実装る場合はcancellationTokenを入れないとエラーが出るので注意！

2024-12-09 13:57 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/StatueOfRhanEffect.cs
> +                }
```suggestion
                }
                
            _cancellationTokenSource.Cancel();
```
UniTaskでする場合は、アイテムを捨てると処理をキャンセルしてもらうようにする

2024-12-09 13:57 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/StatueOfRhanEffect.cs
> +
```suggestion
        private void OnDestroy()
        {
            _cancellationTokenSource.Cancel();
            _cancellationTokenSource.Dispose();
        }
```
ついでにアイテムが壊れるときにもキャンセルしてもらうようにする

2024-12-10 09:01 UTC, IwamotoHinata commented
もし全て修正し終わった後でもコンフリクト起きていたら教えてください。
僕が修正します

2024-12-13 11:15 UTC, nishimura765 commented
ご指摘いただいた部分の修正完了いたしました。
所持アイテムは変更するたびに破壊されてるので、アイテムを捨てたときとplayerが破壊されたときに停止するようにしています。

2024-12-13 11:30 UTC, nishimura765 commented
> もし全て修正し終わった後でもコンフリクト起きていたら教えてください。 僕が修正します。
ありがとうございます。
Push後に確認したところ、まだコンフリクト発生していたので一旦放置しておきます。

2024-12-18 08:16 UTC, IwamotoHinata commented
コンフリクトとりあえず直しました。
BGMManagerの音源リストを弄ったので、ミスがあれば直します

2024-12-18 08:18 UTC, IwamotoHinata commented
@nishimura765 @tibigamePoppo 
石像について質問があります。アイテムデータベースの情報と実装内容が異なるのですが、仕様が変更されたのでしょうか？

2024-12-18 13:53 UTC, tibigamePoppo requested changes
https://www.notion.so/tokushima-igc/2079e6d7ddf94a88ab201e5aa762e5f9
上記の仕様書に沿った値にして欲しいです。
1. アイテム欄にある限り常に効果を発揮する
2. 毎秒SANを0.01減少させる
3. 毎秒HPを0.1回復する（HPの最大値は超えない）
確認したところHPやSANがint型なので、HPは10秒に1減らして、SANは100秒に1減らすようにしてください。

2024-12-18 23:40 UTC, nishimura765 commented
@tibigamePoppo 
了解です。
仕様書通りになるよう修正いたします。

2024-12-19 16:50 UTC, tibigamePoppo approved these changes

2024-12-29 12:19 UTC, tibigamePoppo commented
通します

2024-12-29 12:19 UTC, merged