[アイテム]魔術のホイッスル追加
InnovaGameCreate/mythos-encounter pull request #299
Opened 2024-12-13 12:54 UTC by nishimura765

## 概要

サポートアイテムの魔術のホイッスルを追加しました
## 変更点

変更点1 MagicWhistle.prefabを追加
変更点2 ワープ時の暗転エフェクト追加のためFadeBlackImageを編集

## テスト
 
 動作確認用シーン：Ingame

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-12-15 13:34 UTC, tibigamePoppo requested changes

2024-12-15 13:34 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
> +        }
アイテムの固有処理はMagicWhisleEffectにで行ってほしいです。

2024-12-19 00:16 UTC, nishimura765 commented on Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
> +        }
修正バージョンをプッシュしました。
確認お願いいたします。

2024-12-23 00:34 UTC, tibigamePoppo approved these changes
コードも見た限り問題なさそう
ビルド時にエラーが発生しないことを確認しました。
develop後に動作確認が必要そう

2024-12-25 14:31 UTC, Tyunousause approved these changes
適切に動作しました！

2024-12-29 06:54 UTC, merged