ReadMeにPullRequestの書き方の追加
InnovaGameCreate/mythos-encounter pull request #33
Opened 2024-05-10 10:22 UTC by tibigamePoppo

## 概要

## 変更点

## テスト

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

2024-05-10 10:40 UTC, Tyunousause submitted a review, later dismissed
内容を確認しました。問題無し

2024-05-11 06:55 UTC, IwamotoHinata requested changes
軽いケアレスミスなので修正お願いします

2024-05-11 06:55 UTC, IwamotoHinata commented on README.md
> +プルリクエスト作成後、マージされるためには2人以上のreviewが必要な設定ないっています。作成は下記のようにReviewerを設定してください。
```suggestion
プルリクエスト作成後、マージされるためには2人以上のreviewが必要な設定になっています。作成は下記のようにReviewerを設定してください。
```

2024-05-11 12:37 UTC, IwamotoHinata approved these changes

2024-05-12 09:23 UTC, merged