ステージのオブジェクトのNavMeshの最適化とドアの開閉機能の実装
InnovaGameCreate/mythos-encounter pull request #36
Opened 2024-05-13 14:10 UTC by tibigamePoppo

## 概要

ドアの開閉機能の追加
一部オブジェクトをNavmeshのbake対象外に設定
## 変更点

 - ドアをインタラクトで開閉する機能の実装
 - ステージの小物をNavmeshのbake対象外に設定
## テスト

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

2024-05-15 06:21 UTC, IwamotoHinata submitted a review, later dismissed

2024-05-16 04:15 UTC, Tyunousause requested changes
ドアに向かってダッシュしながら体をこすりつけると埋まったり移動できなくなったりする。
![スクリーンショット (1369)](https://github.com/InnovaGameCreate/mythos-encounter/assets/73172785/80c1d9ef-855b-4ec1-b7ec-68f4a4fda64e)

2024-05-16 12:03 UTC, tibigamePoppo commented
@Tyunousause 
ドアの開閉中は当たり判定をなくすようにしました。

2024-05-17 15:07 UTC, Tyunousause approved these changes
何度か試しましたが無事めり込まずに済みました

2024-05-18 02:32 UTC, merged