Feature/player insunity
InnovaGameCreate/mythos-encounter pull request #37
Opened 2024-05-16 00:40 UTC by IwamotoHinata

## 概要

EyeParalyze以外の発狂系のスクリプトは現時点で作れるところまで作成した。
## 変更点

- BodyParalyze作成
- IncreasePulsation作成
- Scream作成（途中まで）
- Hallucination作成（途中まで）
## テスト

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

PlayerStatusいじってしまったので今後西村君とコンフリクト起きそう...

2024-05-16 01:32 UTC, tibigamePoppo requested changes

2024-05-16 01:32 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
> +                yield return new WaitForSeconds(1.0f);
```suggestion
yield return new WaitForSeconds(5.0f);
``` 
1秒おきはまずいと思ったので、5秒くらいにしてほしいです。

2024-05-16 01:32 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Insanity/Hallucination.cs
> +            _audioListener = transform.Find("Main Camera").gameObject.GetComponent<AudioListener>();
```suggestion
_audioListener = GetComponentInChildren<AudioListener>();
``` 
Findの場合、名前の変化にとても弱くなるので、できるだけ使用を避けたいです。（他の人がこの部分を知らずにMainCameraの名前を変える可能性があるので）なので、子オブジェクトからGetComponentするのはどうでしょう。

2024-05-16 01:32 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/Insanity/Scream.cs
> +            _myPlayerMove.MoveControl(false);
```suggestion

``` 
現状Scream中にBodyParalyzeのマヒが起こると、叫んでいるときでも動けるようになります。
例.
①BodyParaylzeになっている
②Screamになり5秒間動けなくなる
③直後にBodyParaylzeの体のマヒが起こり1秒動けなくなる
④BodyParaylzeのマヒが終わり動けるようなる
◆ここで叫んでる途中でも歩けるようになる◆
⑤Screamの叫ぶのが終わり歩けるようになる。

これを解決するためには、移動不能中はマヒにならない、あるいは下記のように、マヒと叫び声の数値を作り移動速度の計算に組み込むなどがあると思います。
https://github.com/InnovaGameCreate/mythos-encounter/blob/33fd052817afcfe0c6d3c2a3d051eb8b0059a0e4/Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs#L176C1-L179C10

2024-05-16 02:01 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Player/Insanity/Scream.cs
> +            _myPlayerMove.MoveControl(false);
TempPlayerMoveの中に新しく_isCannotMoveByParalyzeというBoolを作成して、Scream.CsとBodyParalyze.Csの「体が動かなくなる処理」の発動条件を分けるようにしました。

2024-05-16 02:05 UTC, tibigamePoppo submitted a review, later dismissed
正常に動くこと確認しました。

2024-05-16 02:05 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
> +            else if(_isCanMove == false || _isCannotMoveByParalyze)
```suggestion
 else if(!_isCanMove || _isCannotMoveByParalyze)
``` 
隣の_isCannotMoveByParalyzeが==trueを省略しているので_isCanMove == falseも省略して!_isCanMove とするのが読みやすいとお思います

2024-05-16 02:05 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
> +                .Where(_ => _isCanMove && _isCannotMoveByParalyze == false)
```suggestion
  .Where(_ => _isCanMove && !_isCannotMoveByParalyze)
``` 
隣の_isCanMoveが==trueを省略しているので、_isCannotMoveByParalyzeも省略して書くのが見やすいかもしれません。
他の_isCannotMoveByParalyze == falseも同様です。

2024-05-16 03:48 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
> +                .Where(_ => _isCanMove && _isCannotMoveByParalyze == false)
今日中に修正しておきます

2024-05-16 12:04 UTC, tibigamePoppo approved these changes

2024-05-17 19:56 UTC, Tyunousause approved these changes
機能しました。スクリプトも大丈夫です。

2024-05-17 19:56 UTC, merged