プレイヤースポーンの修正
InnovaGameCreate/mythos-encounter pull request #39
Opened 2024-05-17 05:43 UTC by KaPiBaR-001

## 概要
ランダムに生成されたSpawnroomにプレイヤーをスポーンさせる

## 変更点

## テスト

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [x] ビルドが成功するかの確認
 
## 問題

2024-05-17 06:48 UTC, tibigamePoppo requested changes
ブランチ名は今回のような機能実装の場合だと
feature/から始めるキャメルケースにしてください。今回の場合だと下記のようになります。
feature/player_spawn

2024-05-17 06:48 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/PlayerSpawn/PlayerSpawner.cs
> +        Vector3 SpawnPosition;
```suggestion
private Vector3 _spawnPosition;
``` 
基本的にprivateを明記してください。また、命名規則に合わせてパスカルケースではなく_から始まるキャメルケースで書いてください。

2024-05-17 06:48 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
> +        public static Vector3 SpawnPosition;
```suggestion
private Vector3 _spawnPosition;
public Vector3 spawnPosition { get => _spawnPosition;}
``` 
基本的にprivateにしてください。
静的にする必要がない場合はstaticを使わないでください。バグの原因になります。
privateを他スクリプトから参照する際はカプセル化を用いて、間接的にgetしてください。
カプセル化の例.
```
public Vector3 spawnPosition { get => _spawnPosition;}
```

2024-05-19 10:54 UTC, IwamotoHinata approved these changes
動作確認問題なかったです

2024-05-19 17:20 UTC, tibigamePoppo approved these changes

2024-05-19 17:20 UTC, merged