疲労時のスタミナ急速回復機能
InnovaGameCreate/mythos-encounter pull request #40
Opened 2024-05-17 13:55 UTC by nishimura765

## 概要

スタミナがきれたときにスタミナ値がはやく回復できるようにしました。
## 変更点

変更点１　スタミナがきれてから回復するまでのラグを少し追加
## テスト

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

2024-05-17 20:09 UTC, Tyunousause requested changes
他のスクリプトと文字コードを合わせてほしいです。シフトJISでお願いします

2024-05-19 23:18 UTC, tibigamePoppo reviewed
仕様書に書いてなくて申し訳ないですが、スタミナをすべて消費後は最大になるまで走れないようにしてください。

2024-05-21 07:55 UTC, IwamotoHinata requested changes

2024-05-21 07:55 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
> +            yield return new WaitUntil(() => _myPlayerStatus.nowStaminaValue縲> 10);//繧ｹ繧ｿ繝溘リ縺10縺ｫ縺ｪ繧九∪縺ｧ蝗槫ｾｩ縺吶ｋ縺ｮ繧貞ｾ�▽
```suggestion
            yield return new WaitUntil(() => _myPlayerStatus.nowStaminaValue >= 100);
```
上のように変更を行えば、スタミナが全回復するまでダッシュができないようになると思います

2024-05-22 00:30 UTC, closed without merging