InGameシーンでエネミーが動くようにし、スポーン直後のPlayerに接近しないようにした
InnovaGameCreate/mythos-encounter pull request #41
Opened 2024-05-17 14:53 UTC by Tyunousause

## 概要

InGameシーンでエネミーが動くようにした。スポーン直後のPlayerに接近しないようにした

## 変更点

- InGameシーンでEnemySpwanerの設定をすました
- EnemySpawnerがゲーム開始時に敵の作成に成功したことをInGameManagerに通知するようになった
- 生成直後のEnemyがすぐに探索先をPlayerのいる位置にしないようにした

## テスト

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

-視界のマッピングは二階建てとドアに対応したらやります

## 作り直す前のプルリクエストに対する返答
-RightCheckの配列の範囲外であるという内容のエラーは、その前にあるzが範囲外というDebugLogErrorの条件を満たすようにマップ作成時のxz方向の広さを調節することで解決します。おそらくこれが発生した時はプレイヤーが壁の外にいたはず。

2024-05-19 23:28 UTC, tibigamePoppo approved these changes
- InGameシーンでEnemySpwanerの設定をすました
 - EnemySpawnerがゲーム開始時に敵の作成に成功したことをInGameManagerに通知するようになった
 
上記の動作確認を行いました。

2024-05-20 00:49 UTC, IwamotoHinata requested changes
![スクリーンショット 2024-05-20 094102](https://github.com/InnovaGameCreate/mythos-encounter/assets/86921212/d070445b-fb41-4f4f-a068-331f2d09ffa6)
SetGridWatchNum関数の方でもエラーが出ていました。（下から4番目）
もし、これがマップ作成時のxz方向の広さを調節することで解決するのであれば問題ないです。

まだ数回しか試していませんが、このバグ再現性が低いかもしれません。まだ一回しか確認できず、原因がわかっていません

2024-05-21 08:03 UTC, IwamotoHinata commented
@Tyunousause 
あれから何度か試して、１回だけエラー出ました。
Debug.LogErrorでxz座標に関してのエラーが表示されていたので設定の問題かもしれません。設定の問題を解決したら改めて検証してみたいと思います。

2024-05-21 08:04 UTC, IwamotoHinata commented
@tibigamePoppo @Tyunousause 
このプルリク通してしまっていいですか？設定の問題が解消されるまで待っておいた方がいいですか？

2024-05-22 00:32 UTC, tibigamePoppo commented
@Tyunousause 
修正ありがとうございます。
後はコンフリクトの修正だけお願いします。

2024-05-23 17:27 UTC, tibigamePoppo approved these changes

2024-05-24 14:22 UTC, IwamotoHinata approved these changes

2024-05-24 14:22 UTC, merged