脱出アイテム数の表示
InnovaGameCreate/mythos-encounter pull request #43
Opened 2024-05-21 08:48 UTC by twink-star

## 概要
右上に脱出アイテムの数を表示

## 変更点
-SceneのInGame_Stage_Copyを作成
-IngameManager.csの_getEscapeItemCountをReactivePropertyに
-EscapeItemPresenter.csを追加

## テスト

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [x] ビルドが成功するかの確認
 
## 問題

2024-05-21 08:59 UTC, tibigamePoppo requested changes
今回pngやwav、projectSettingなどがpushされていますが、今回の変更と関係していますか？

2024-05-21 09:16 UTC, IwamotoHinata commented
> 今回pngやwav、projectSettingなどがpushされていますが、今回の変更と関係していますか？

これ俺が発狂関連の実装の時に追加したpngやwavですね。

2024-05-21 09:32 UTC, tibigamePoppo commented
> > 今回pngやwav、projectSettingなどがpushされていますが、今回の変更と関係していますか？
> 
> これ俺が発狂関連の実装の時に追加したpngやwavですね。

ということはおそらく今回の作業内容とは関係がないと思いますので、pushから外してください。

2024-05-21 10:52 UTC, tibigamePoppo commented
> > ということはおそらく今回の作業内容とは関係がないと思いますので、pushから外してください。
> > すみません、どの辺を触ればpushから外れるのかがわからないので教えてほしいです

使用しているツールはなんでしょうか?
(gitbashやgithubdesktopなど)

2024-05-21 12:00 UTC, twink-star commented
> 使用しているツールはなんでしょうか? (gitbashやgithubdesktopなど)

GitHub Desktopです

2024-05-21 12:45 UTC, IwamotoHinata commented
[https://docs.github.com/ja/desktop/managing-commits/reverting-a-commit-in-github-desktop](url)
この方法を試してみてください

2024-05-21 12:45 UTC, IwamotoHinata commented
@twink-star
[https://docs.github.com/ja/desktop/managing-commits/reverting-a-commit-in-github-desktop](url)
この方法を試してみてください

2024-05-21 12:47 UTC, IwamotoHinata commented
https://docs.github.com/ja/desktop/managing-commits/reverting-a-commit-in-github-desktop
@twink-star 
この方法を試してみてください

2024-05-21 14:03 UTC, IwamotoHinata commented
@twink-star 
コミットする前の状態（何の変更を適用させるか選べる状態）に戻りましたか？

2024-05-21 14:09 UTC, twink-star commented
もどりました

2024-05-21 15:28 UTC, IwamotoHinata commented
@twink-star 
ありがとうございます。
それでは、今回自分が変更した内容以外のチェックを外して、再度pushをお願いします！

2024-05-21 17:50 UTC, twink-star commented
すみません、質問を勘違いしてました
GitHubDesktop上でcommitする前の状態には戻ってないです
今こうなってます
![スクリーンショット (15)](https://github.com/InnovaGameCreate/mythos-encounter/assets/136770998/9646b60d-ed15-4c7c-bab4-48a1c2622942)

2024-05-21 18:00 UTC, IwamotoHinata commented
@twink-star 
全部なくなってる...；；
申し訳ないのですが、もう一度作業を１からお願いしてもよろしいでしょうか？
https://github.com/InnovaGameCreate/mythos-encounter/pull/43/commits/9a1d3f85784b258c9605a44700ac707988cf332f
ここに以前の作業内容が残っているので、コピペを駆使するとすぐに終わると思います。

2024-05-21 19:06 UTC, twink-star commented
戻してcommitしました。
これで問題ありませんか？

2024-05-22 00:28 UTC, tibigamePoppo requested changes
動作確認を行い正常に動作することを確認しました。

現在スクリプトがResultCanvasにありますが、これは結果を表示するためのものなので、もう一つ別にUI用のcanvasを作って、そこにスクリプトをアタッチしてください。また、それをprefabにしておいてください。

2024-05-22 10:26 UTC, twink-star commented
canvasを作成しました

2024-05-22 11:31 UTC, tibigamePoppo submitted a review, later dismissed

2024-05-23 04:17 UTC, IwamotoHinata requested changes
スクリプトの修正だけお願いします。
動作自体は問題ありませんでした。

2024-05-23 04:17 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/System/UI/EscapeItemPresenter.cs
> +        }
```suggestion

        void Start()
        {
            IngameManager ingamemanager = IngameManager.Instance;
            ingamemanager.OnEscapeCount.Subscribe(x => {
                _socreText.text = "�E�o�A�C�e����: " + x;
            }).AddTo(this);
        }
```
IngameManagerはシングルトンで設計されているので、上記のようにすると簡単に取得できます。

2024-05-23 12:47 UTC, tibigamePoppo approved these changes

2024-05-23 18:32 UTC, IwamotoHinata approved these changes

2024-05-23 18:32 UTC, merged