スタミナ消費後の急速回復
InnovaGameCreate/mythos-encounter pull request #44
Opened 2024-05-21 15:28 UTC by nishimura765

## 概要

スタミナ消費後にスタミナが速く回復する機能追加
編集していたスクリプトが更新されていたため、新たにブランチを作りました。
## 変更点

変更点１文字コードをShift JISに変更
変更点２スタミナが完全回復するまで走行不可になるよう修正
## テスト

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

2024-05-21 16:22 UTC, IwamotoHinata submitted a review, later dismissed
文字化けしてませんでした。

2024-05-21 16:45 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
>              }
if(!_isTiredPenalty)
{
処理A
}else if(_isTiredPenalty)
{
処理B
}
となっているのを
if(_isTiredPenalty)
{
処理B
}else )
{
処理A
}
にした方がシンプルでわかりやすいです

2024-05-21 16:47 UTC, Tyunousause requested changes
if文が難解になっているのを修正してほいいです

2024-05-22 06:25 UTC, nishimura765 commented
指摘された部分を修正しました。
修正した後pushしましたが、もう一度プルリクエストする必要はないですか？

2024-05-22 06:37 UTC, IwamotoHinata commented
> 指摘された部分を修正しました。 修正した後pushしましたが、もう一度プルリクエストする必要はないですか？

プルリクはしなくて大丈夫です！

2024-05-22 06:40 UTC, IwamotoHinata approved these changes

2024-05-22 11:30 UTC, tibigamePoppo approved these changes

2024-05-23 16:14 UTC, Tyunousause approved these changes
修正を確認しました

2024-05-23 16:15 UTC, merged