ステージの二階の生成
InnovaGameCreate/mythos-encounter pull request #45
Opened 2024-05-22 16:35 UTC by tibigamePoppo

## 概要

ステージで２階が生成されるように機能実装
## 変更点

 - 階段付きの部屋の追加
 - 階段のプレファブの修正
 - ステージで2階生成する機能の実装
 - ステージで階段付きの部屋を生成する機能の実装
## テスト

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

2024-05-23 04:34 UTC, IwamotoHinata requested changes
変更内容の自由落下では動作がふわっとしてました。そこだけ修正すると違和感ないと思います。
二階部分の作成に関しては問題ありませんでした。

2024-05-23 04:34 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
> +                _characterController.Move(new Vector3(0, -9.8f * Time.deltaTime, 0) * moveSpeed * 10 * Time.deltaTime);
```suggestion
                _characterController.Move(new Vector3(0, -9.8f * Time.deltaTime, 0));
```
試してみましたがこっちの方が自然な自由落下だと思います。

2024-05-26 08:44 UTC, Tyunousause requested changes
電灯が床を貫通しているのを修正してほしい
階段付近で、ドアが2つ重なると挙動がおかしい（おそらくコライダーが重なる→弾ける→Vector3.Slerp）で動く？
これは開閉中のアニメーションでコライダーをオフにするfeature/stage_prefab_navmesh_modifyブランチをこのブランチにマージしても発生するので移動中ではなく移動後の位置に問題があると思われる

https://github.com/InnovaGameCreate/mythos-encounter/assets/73172785/fbbe21e8-e11c-43f4-a83c-046a07500f89

2024-05-26 13:08 UTC, tibigamePoppo commented
> ![スクリーンショット (1398)](https://private-user-images.githubusercontent.com/73172785/333866178-c6b94b7d-73da-4570-8d45-65353b94f2b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MjkwNjMsIm5iZiI6MTcxNjcyODc2MywicGF0aCI6Ii83MzE3Mjc4NS8zMzM4NjYxNzgtYzZiOTRiN2QtNzNkYS00NTcwLThkNDUtNjUzNTNiOTRmMmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEzMDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1Y2NiN2QwNWMxOThkZGY3MjA3ZjdjNjk4ODY0ZGQ1YzM4ZDEyYjJhYjEzODhjNzMxYzkxNGVmMTNiMDc0MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N_rHca7Mo1VYNKkcP2FbGbRXXuZEn46rwmbCWCrSxFE) 電灯が床を貫通しているのを修正してほしい、画面中央の床

現状の2階の高さは壁の高さ準拠にしているため、床の位置を変更することはできません。
なのでプレファブをいじらないといけないですが、いじれないのでこのブランチでは修正できません。

2024-05-27 06:17 UTC, Tyunousause approved these changes
了解です。issueの方に書いときます

2024-05-27 10:33 UTC, merged