ステージ生成後のアイテム生成機能の実装
InnovaGameCreate/mythos-encounter pull request #47
Opened 2024-05-24 12:27 UTC by tibigamePoppo

## 概要

ステージ生成後のアイテム生成機能の実装
## 変更点

 - ステージ生成後にMarkerを頼りにアイテムを生成する機能の実装
 - escapeアイテムをインタラクトで取得するように機能変更
## テスト

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

- テストする際はresourceにあるImtemGeneraterをシーンにアタッチして使用してください。

2024-05-26 05:41 UTC, IwamotoHinata commented
@tibigamePoppo
試せるシーンってありますか？

2024-05-26 07:41 UTC, tibigamePoppo commented
stageGeneraterでステージを生成してるシーンなら基本的に試せます。
ただし、テストする際はresourceにあるImtemGeneraterをシーンにアタッチして使用してください。

2024-05-26 07:42 UTC, tibigamePoppo commented
@IwamotoHinata 
stageGeneraterでステージを生成してるシーンなら基本的に試せます。
ただし、テストする際はresourceにあるImtemGeneraterをシーンにアタッチして使用してください。

2024-05-26 09:28 UTC, Tyunousause reviewed
アイテムジェネレータープレハブをInGame_Stageに追加してテスト
itemgenerater.csにてエラー発生、
NullReferenceException: Object reference not set to an instance of an object
Scenes.Ingame.Stage.ItemGenerator.Awake () (at Assets/Scripts/Scenes/InGame/Stage/ItemGenerator.cs:27)
おそらくIngameManager.csのAwakeとItemGenerator.csのAwakeの実行順番が固定されていないのが原因。

2024-05-26 09:28 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Stage/ItemGenerator.cs
> +        private List<GameObject> _escapeItems;
GitHubで文字化けしてしまっているが、ここのToolTipのStageItemの説明が多分間違っている。
また、escapeItemsはエスケープアイテムまたはステージアイテムが設置される位置になる設計のはずなのでタグのように_itemSpawnsみたいな名前の方がいいと思う

2024-05-26 13:00 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Stage/ItemGenerator.cs
> +        private List<GameObject> _escapeItems;
[799b32e](https://github.com/InnovaGameCreate/mythos-encounter/pull/47/commits/799b32e5bdf638e37f7cb2a7a5f949297710c339)
これで修正した

2024-05-27 06:24 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Stage/ItemGenerator.cs
> +        private List<GameObject> _escapeItems;
りょ

2024-05-27 06:44 UTC, Tyunousause requested changes
エラー発生しました
foreach周りです

2024-05-27 06:50 UTC, Tyunousause requested changes
エラー発生しました。
foreach周りです

2024-05-27 06:50 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Stage/ItemGenerator.cs
> +        }
: Collection was modified; enumeration operation may not execute.
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <6aa56e57ab504395b555cf3ed50fa53d>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <6aa56e57ab504395b555cf3ed50fa53d>:0)
Scenes.Ingame.Stage.ItemGenerator.ClearList () (at Assets/Scripts/Scenes/InGame/Stage/ItemGenerator.cs:74)
Scenes.Ingame.Stage.ItemGenerator.<Start>b__6_0 (UniRx.Unit _) (at Assets/Scripts/Scenes/InGame/Stage/ItemGenerator.cs:34)
UniRx.Observer+Subscribe`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/Observer.cs:165)
UniRx.Subject`1[T].OnNext (T value) (at Assets/Plugins/UniRx/Scripts/Subjects/Subject.cs:62)
Scenes.Ingame.Manager.IngameManager.SetReady (Scenes.Ingame.InGameSystem.ReadyEnum ready) (at Assets/Scripts/Scenes/InGame/Manager/IngameManager.cs:81)
Scenes.Ingame.Stage.StageGenerator.Generate (System.Threading.CancellationToken token) (at Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs:94)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at Assets/Plugins/UniTask/Runtime/UniTaskScheduler.cs:90)
Scenes.Ingame.Stage.<Generate>d__32:MoveNext() (at Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs:94)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start(<Generate>d__32&) (at Assets/Plugins/UniTask/Runtime/CompilerServices/AsyncUniTaskVoidMethodBuilder.cs:110)
Scenes.Ingame.Stage.StageGenerator:Generate(CancellationToken)
Scenes.Ingame.Stage.StageGenerator:Start() (at Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs:81)
エラー。foreach中にListの内容が変わると発生する奴だった...はず

2024-05-27 13:31 UTC, Tyunousause approved these changes
エラースクリプト動作すべてにおいて問題なしです

2024-05-27 13:51 UTC, merged