UniTaskの追加とIngameManagerの作成
InnovaGameCreate/mythos-encounter pull request #6
Opened 2024-04-06 07:54 UTC by tibigamePoppo

## 概要

UniTaskの追加とIngameManagerの追加
ResourcesのPrefabの中にInGameManagerを追加したので、自分で使うシーンに追加してください。
## 変更点

- UniTaskの追加
- InGameManagerの追加

## テスト

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

2024-04-06 13:50 UTC, EndouYuma commented
消せないコメントを送ってみよう

2024-04-06 14:37 UTC, IwamotoHinata requested changes
InGameReady.Csの24,25行目について
全てStageReadyを変更しているのですが、PlayerReadyとEnemyReadyが変更されていないです。

2024-04-07 02:04 UTC, Tyunousause commented
重すぎるゆえにここで失礼
InGameReady.Cs　24と25行目のelse ifのelseを消す必要あり。
InGameManager.Csの63と64行目のelse ifのelseを消す必要あり。

このスクリプトの含まれるシーンのビルド及び実行は成功した

2024-04-07 02:28 UTC, Tyunousause commented
当該シーンのビルド及び実行成功、エラーなし

2024-04-07 05:29 UTC, tibigamePoppo commented
@IwamotoHinata 
[be33a0f](https://github.com/InnovaGameCreate/mythos-encounter/pull/6/commits/be33a0f0b2a127357eb7ef1d231294e229d573f8)
InGameReadyの修正をしました。

2024-04-07 12:36 UTC, Tyunousause commented
@tibigamePoppo 
SetReadyメソッドはまさかとは思うがすべて3つある引数すべてにtrueが入力されていないことを前提に設計されてはないよね？

2024-04-07 13:41 UTC, IwamotoHinata approved these changes
確認しました

2024-04-07 15:59 UTC, tibigamePoppo commented
@Tyunousause 
SetReadyメソッドの引数については3つのうちどれか1がtrueで与えられるものとして設計しています。
そもそも、各要素が個別で来るため、2つ同時に来ることがないからです。

2024-04-08 08:12 UTC, Tyunousause commented
@tibigamePoppo ほな3つともtrueが与えられたらエラーメッセージ表示するのはどう？

2024-04-08 08:45 UTC, Tyunousause commented
@tibigamePoppo 
了解です、手が空いてるとき出ればでいいからtrue2個以上来たら警告出したりするのはどう？

2024-04-08 08:52 UTC, Tyunousause approved these changes
確認しました。2つ以上true来たら警告とか出してもいいかも？

2024-04-08 08:52 UTC, merged