[WIP]統合作業（現在作業中なのでレビューはまだ大丈夫です）
InnovaGameCreate/mythos-encounter pull request #61
Opened 2024-05-27 23:08 UTC by tibigamePoppo

## 概要

integration_4_19以降の変更点をInGameに統合
## 変更点

- Find("Player")の部分をtagによって検索するように修正
- IngameManagerのイベントにキャラクター生成時のイベントの追加
- キャラクター生成をステージ生成後に行うように変更
- 敵キャラクター生成をキャラクター生成後に行うように変更
- ドア開閉スクリプトの修正

## テスト

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
 動作確認用シーン：
## 問題

現在作業中なのでレビューはまだ大丈夫です。

2024-05-28 05:38 UTC, Tyunousause commented
@tibigamePoppo 
enemySpowner.csのインスペクター上のceterpositionとx,z,rangeを設定すればエラー出ないはずです。ceterpositionは最もx,z座標の値が小さい床のパネルの中心を指定して、x,zそれぞれx方向z方向の床の枚数、rangeは床のパネルの間隔を指定してあげてください

2024-05-30 13:24 UTC, IwamotoHinata submitted a review, later dismissed
InGame内で問題はなかったです

2024-05-31 02:05 UTC, Tyunousause requested changes
EnemySpownerのxとzを19にしてほしいです。マップの端っこが探索対象になってないです

2024-06-01 06:09 UTC, tibigamePoppo commented
> EnemySpownerのxとzを19にしてほしいです。マップの端っこが探索対象になってないです
修正しておきました

2024-06-01 06:11 UTC, Tyunousause requested changes
プロジェクトを開けようとするとUnityがセーフモードになります
ブランチの最新状態を見るにDetectionMagic.csのコンフリクトが解消されていません。

2024-06-01 11:34 UTC, tibigamePoppo commented
> プロジェクトを開けようとするとUnityがセーフモードになります ブランチの最新状態を見るにDetectionMagic.csのコンフリクトが解消されていません。

今度こそ問題ないはず

2024-06-01 14:14 UTC, Tyunousause approved these changes
今度こそ大丈夫！

2024-06-01 14:21 UTC, merged