スタミナゲージの残量による色変更
InnovaGameCreate/mythos-encounter pull request #66
Opened 2024-05-31 10:37 UTC by twink-star

## 概要

スタミナの残量によってスタミナゲージの色が変わるようにした

## 変更点

-StaminaColor.csを作成
-PlayerStatus.csにInstanceを追加

## テスト
 
 動作確認用シーン：

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [x] ビルドが成功するかの確認
## 問題

2024-05-31 12:53 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
> +            Instance = this;//�C���X�^���X�̏�����
```suggestion

``` 
一般的にマネージャーなどではない場合はシングルトンでは実装しないでください

2024-05-31 12:54 UTC, tibigamePoppo requested changes
プレイヤーのpresenterはすでにPlayerGUIPresenter があるので、そこで実装してください

2024-06-09 12:40 UTC, tibigamePoppo requested changes
StaminaColorを使用していない場合は消してください。
また、動作確認できるシーン名を教えてください。

2024-06-11 10:17 UTC, twink-star commented
InGameで動作確認しました

2024-06-11 11:13 UTC, tibigamePoppo approved these changes

2024-06-12 06:08 UTC, IwamotoHinata approved these changes

2024-06-12 06:08 UTC, merged