Feature/enemy spowner
InnovaGameCreate/mythos-encounter pull request #7
Opened 2024-04-07 13:22 UTC by Tyunousause

## 概要

## 変更点

- 名前を指定して座標を指定せずEnemyをスポーン
- 名前と座標を指定してEnemyをスポーン

## テスト

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認

2024-04-07 16:00 UTC, tibigamePoppo requested changes
シーンが再生できませんでした。
エラーメッセージ：UnassignedReferenceException: The variable testEnemy of EnemySpawner has not been assigne
おそらくSpawnerにPrefabがセットされていないのだと思います。

2024-04-08 07:09 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
> +namespace Scenes.Ingame.Enemy
無いです、ミスですね直します

2024-04-09 06:52 UTC, tibigamePoppo approved these changes

2024-04-09 06:54 UTC, IwamotoHinata approved these changes
確認が遅れてすみません。
シーン再生時に無事敵がスポーンされたことを確認しました。

2024-04-09 07:08 UTC, merged