StageGeneraterを追加のステージprefabに対応した
InnovaGameCreate/mythos-encounter pull request #71
Opened 2024-06-03 22:47 UTC by tibigamePoppo

## 概要

StageGeneraterを追加のステージprefabに対応した
## 変更点

 - 4x2と2x4の通路の装飾の生成機能の実装
 - 3x3の階段のprefabの置き換え
 - 2x2,2x3,3x2の複数種類の部屋がある場合のランダム生成機能の実装
 - 一部処理にコメントアウトの追加
## テスト
 
 動作確認用シーン：Ingame_Stage

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-06-04 09:33 UTC, IwamotoHinata requested changes
![スクリーンショット 2024-06-04 183144](https://github.com/InnovaGameCreate/mythos-encounter/assets/86921212/1444418f-db10-4acf-8523-3ce99538cc91)

装飾品生成の機能について。
写真のように2*4 , 4*2 の判断を間違えて生成された装飾品が他の部屋に侵食しています

2024-06-05 14:11 UTC, IwamotoHinata requested changes
![スクリーンショット 2024-06-05 230903](https://github.com/InnovaGameCreate/mythos-encounter/assets/86921212/38f8824c-ad23-46a1-9b79-9624268b1150)
ずれていた原因が分かりました。
StagePrefabPoolスクリプト内のCorridorPrefabsに入っているプレハブが間違ってました。

2024-06-07 11:19 UTC, tibigamePoppo commented
> ![スクリーンショット 2024-06-05 230903](https://private-user-images.githubusercontent.com/86921212/336873640-38f8824c-ad23-46a1-9b79-9624268b1150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTkzOTQsIm5iZiI6MTcxNzc1OTA5NCwicGF0aCI6Ii84NjkyMTIxMi8zMzY4NzM2NDAtMzhmODgyNGMtYWQyMy00NmExLTliNzktOTYyNDI2OGIxMTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDExMTgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjM2I2NjVlYTYyYzdjZTUzM2IyOTEzNDI4ZDE0NmQzZTk1YzY4OWU4NzcwNzRlODMyZTUzYTllNzZhODBjZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JrOupZa_IYJlx-k4BZB0nXOkCKMhSil9-hkLy-BHg7U) ずれていた原因が分かりました。 StagePrefabPoolスクリプト内のCorridorPrefabsに入っているプレハブが間違ってました。

こっち視点はprefabはあってるんですよね。
一応IngameとIngame_stageで動作確認するとどちらも正常に動作することは確認できたんですが。
どうして違いがでるんでしょう。
![image](https://github.com/InnovaGameCreate/mythos-encounter/assets/67269447/c23cc8a8-b158-43a7-a423-25b0bff1e75a)

2024-06-10 05:06 UTC, IwamotoHinata approved these changes

2024-06-10 08:31 UTC, Tyunousause requested changes
壁の中にめり込んだドアが生成されてしまいます
![Uploading スクリーンショット (1409).png…]()

2024-06-10 11:02 UTC, tibigamePoppo commented
@Tyunousause 
画像が見れないので、詳しくは状況はわかりませんが、画面端の場合は現状プログラム上かかならず起こるバグとなっています。
現在は、別途上から使用不可にするプレファブ（木の板等）を製作してもらっており、それを上からかぶせることで、使用できないようにする予定です。

2024-06-10 11:06 UTC, tibigamePoppo commented
あ、ごめん。ミスって岩本君にもrequest reviewしてしまったわ

2024-06-10 11:18 UTC, IwamotoHinata approved these changes
👍🏻

2024-06-10 14:17 UTC, Tyunousause approved these changes
了解しました

2024-06-10 14:17 UTC, merged