棚の開閉
InnovaGameCreate/mythos-encounter pull request #79
Opened 2024-06-14 06:50 UTC by KaPiBaR-001

## 概要
棚を右クリックで開閉できるようにした

## 変更点

変更点1:スクリプトStageRackを作成
変更点2:プレハブKitchen_Module_03_Door_LOD0にStageRackをアドコンポーメントした
変更点3:プレハブKitchen_Module_03_Door_LOD0のレイヤーをitemに変更
## テスト
 
 動作確認用シーン：Rack_open

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [x] ビルドが成功するかの確認
## 問題

2024-06-14 09:23 UTC, tibigamePoppo requested changes
正常に動作することはできました。
スクリプトをアタッチするprefabですが、3x3Roomではなく下記のprefabでお願いします。
Kitchen_Module_01
Kitchen_Module_02
Kitchen_Module_03
Kitchen_Module_04
Toilet_Cabinet
Wardrobe_04

また、WallXDoor_HH.prefabは変更しないでください。

2024-06-14 09:24 UTC, tibigamePoppo commented on Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/WallXDoor_HH.prefab
> +  m_PrefabAsset: {fileID: 0}
```suggestion
``` 
不要な部分

2024-06-19 13:32 UTC, IwamotoHinata commented
@KaPiBaR-001 
今細川君が作業しているブランチにはないと思うのですが、IInstractableインタフェースに「ReturnPopString」という関数を追加しているので、今後また追加の方をお願いします。StageDoorスクリプトにあるのをコピペしたら問題ないと思います。

2024-06-19 14:17 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Stage/StageRack_Right.cs
> +    public class StageRack_Right : MonoBehaviour, IInteractable
```suggestion

``` 
StageRack_LeftとStageRack_Rightの違いが明ける方向だけであれば。わざわざ別のスクリプトにする必要はないと思います。
[SerializeField]で外部から触れる列挙型(enum)を作って、それで制御を分けるようにしてみれはどうでしょうか。そして、それに今後作るであろう引き出しも入れてみてはどうでしょう。列挙型の例は下記ようになります。
```c#
enum drawType() {//開けるタイプを列挙
RightOpen,//右向きにあける
LeftOpen,//左向きにあける
DrawOpen,//引いて開ける
}
``` 
これを```RackOpen()``` と```RackClose()``` 内でif文で分岐させて処理するとできると思います。

2024-06-20 17:21 UTC, KaPiBaR-001 commented on Assets/Scripts/Scenes/InGame/Stage/StageRack_Right.cs
> +    public class StageRack_Right : MonoBehaviour, IInteractable
列挙体を使ってスクリプトをまとめたいと思います
ありがとうございます

2024-06-21 00:39 UTC, tibigamePoppo requested changes
動作確認した結果、うまく動いてました。

修正してほしい場所はコメントに書いたこと以外にPrefabのWallXDoor_HHにWallYDoor_HHが追加されているため、それを消してほしいです。

2024-06-21 00:39 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Stage/StageRack.cs
> +                });
```suggestion
                transform.DORotate(R_OPENVALUE, 1).SetRelative(true).SetEase(Ease.InOutSine).OnComplete(() =>
                {
                    AnimationcComplete();
                });
            }
            else if (drawType == DrawType.LeftOpen)
            {
                transform.DORotate(L_OPENVALUE, 1).SetRelative(true).SetEase(Ease.InOutSine).OnComplete(() =>
                {
                    AnimationcComplete();
                });
            }
            else if (drawType == DrawType.DrawOpen)
            {
                transform.DOMove(0.3f * D_OPENVALUE, 1).SetRelative(true).SetEase(Ease.InOutSine).OnComplete(() =>
                {
                    AnimationcComplete();
                });
``` 
参考元のStageDoorが少し悪い部分がありますが、今回のような同じ内容の処理が多くある場合は、関数として別に置くと、後からの変更に強くなるため別にした方が良いです。

2024-06-21 00:39 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Stage/StageRack.cs
> +    }
```c#

        private void AnimationcComplete()
        {
            _rackCollider.isTrigger = false;
            _isAnimation = false;
        }
``` 
このように関数にまとめて、RackOpen()とRackClose()から呼び出すようにすると、もし仕様が変わった際に6カ所を修正することにならずにここだけ修正すればよくなります。

2024-06-21 09:46 UTC, KaPiBaR-001 commented on Assets/Scripts/Scenes/InGame/Stage/StageRack.cs
> +    }
次回以降のタスクで,共通する部分を関数にまとめて呼び出すよう意識したいと思います

2024-06-21 09:51 UTC, tibigamePoppo approved these changes

2024-06-21 13:05 UTC, tibigamePoppo approved these changes

2024-06-22 03:45 UTC, IwamotoHinata approved these changes
動作確認問題ありませんでした。

2024-06-22 03:45 UTC, merged