プレイヤーのステータス関係の仮実装
InnovaGameCreate/mythos-encounter pull request #8
Opened 2024-04-09 06:46 UTC by IwamotoHinata

・体力,スタミナ,SAN値の実装
・出血状態の仮実装

## 概要

## 変更点

## テスト

 - [] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [] 命名規則の統一
 - [] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
 
## 問題

2024-04-09 07:06 UTC, tibigamePoppo requested changes

2024-04-09 07:06 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/DisplayPlayerStatusManager.cs
> +        public void ChangeSliderValue(int value , int ID, string mode)
UIに関してですが、UniRxを使う場合は、折角ですのでMVRPパターンで設計してみてはどうでしょうか。
今回の場合ですと、PlayerStatusのOnPlayerHealthChangeをSubscribeして、そこからUIのSliderやTMPを変える形にすると良いと思います。
参考：https://qiita.com/toRisouP/items/5365936fc14c7e7eabf9

2024-04-09 07:06 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
> +        [SerializeField] private IntReactiveProperty _san = new IntReactiveProperty(0);//SAN�l
```suggestion
[SerializeField] private IntReactiveProperty _health = new IntReactiveProperty();//HP.�[���ɂȂ�Ǝ��S
[SerializeField] private IntReactiveProperty _stamina = new IntReactiveProperty();//�X�^�~�i
[SerializeField] private IntReactiveProperty _san = new IntReactiveProperty();//SAN�l
``` 
初期値をInitで入れる場合は、こちたで初期値を入れる必要はないと思います。

2024-04-09 07:06 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
> +            _displayPlayerStatusManager = GameObject.Find("DisplayPlayerStatusManager").GetComponent<DisplayPlayerStatusManager>();
```suggestion
_displayPlayerStatusManager = FindObjectOfType<DisplayPlayerStatusManager>();
``` 
このままだとGameObjectの名前が変更された際に簡単にエラーを吐くので、このやり方の場合はFindObjectOfTypeを使う方が良いです。また、別のコメントで書きますが、UI系の場合はこちらからGetComponentするのではなく、向こうからGetComponentさせた方が良いです（詳しくはMVRPパターン）

2024-04-09 07:17 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Player/DisplayPlayerStatusManager.cs
> +        public void ChangeSliderValue(int value , int ID, string mode)
調べて一度やってみます。ありがとうございます‼

2024-04-09 13:36 UTC, tibigamePoppo requested changes

2024-04-09 13:36 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/PlayerGUIPresenter.cs
> +                                _displayPlayerStatusManager.ChangeSliderValue(x, playerStatus.playerID, "Health");
```suggestion

``` 
MVRPを使う場合はpresenterがviewの値を変更させるので、現状だとDisplayPlayerStatusManager を介しているのでMVRPからそれてしまいます。解決策としてはDisplayPlayerStatusManager のChangeSliderValueないの処理をこちらのPlayerGUIPresenterで行うと良いと思います。
当たら現状の問題点
数値が変わった際の挙動を
PlayerStatus→PlayerGUIPresenter→DisplayPlayerStatusManager →text&slider
を
PlayerStatus→PlayerGUIPresenter→text&slider
にする。

2024-04-09 13:36 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Player/PlayerGUIPresenter.cs
> +                .Subscribe(_ =>
```suggestion
            _displayPlayerStatusManager.OnCompleteSort
                .FirstOrDefault()
                .Subscribe(_ => 
``` 
1度しかイベントは発行されない設計ですが、念のためにSubscribe側でも1度しか受け取らないようにしておくと安全です。
フィルタリング処理は面白いので、今後使う際は見ておくと良いかもしれません。
参考：https://light11.hatenadiary.com/entry/2018/11/17/150424

2024-04-10 02:32 UTC, tibigamePoppo commented
スクリプトについて特に問題ないと思います。

2024-04-10 02:32 UTC, tibigamePoppo approved these changes

2024-04-10 19:47 UTC, Tyunousause approved these changes
ビルド成功、エラー発生せず、正常に稼働を確認。スクリプトの確認も完了しました！

2024-04-10 19:47 UTC, merged