アドレナリン注射器実装
InnovaGameCreate/mythos-encounter pull request #88
Opened 2024-06-21 12:11 UTC by nishimura765

## 概要

アドレナリン注射器(スタミナ減少値を半減するサポートアイテム)を実装しました。
## 変更点

変更点1 ItemPrefabにAdrenalieSyringeを追加
変更点2 PlayerStatus.csを一部編集
## テスト
 
Ingame_Player
 動作確認用シーン：

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

2024-06-23 09:17 UTC, tibigamePoppo approved these changes

2024-06-25 12:32 UTC, IwamotoHinata submitted a review, later dismissed
動作確認問題なしです！

2024-07-03 01:41 UTC, tibigamePoppo commented
コンフリクトを直してください

2024-07-03 20:20 UTC, nishimura765 commented
遅れて申し訳有りません。
コンフリクト解消作業を行いました。

2024-07-04 01:30 UTC, tibigamePoppo approved these changes

2024-07-06 13:30 UTC, Tyunousause requested changes
GitHub上のスクリプトを指定して直接レビューがかけず失礼。
AdrenalineSyringeEffect.csの51行目のdebug.Logは包帯使用ではないのでアドレナリン使用のコルーチンと書いてほしいです

2024-07-11 23:32 UTC, closed without merging