Feature/enemy/recognize door b
InnovaGameCreate/mythos-encounter pull request #98
Opened 2024-06-28 13:51 UTC by Tyunousause

## 概要

ドアを認識する機能と、マップのスキャンを三次元化しました。

## 変更点

-ドアを認識してドアの向こう側を見えないようにしました
-配列を3次元化け
## テスト
 
 動作確認用シーン：

 - [x] 複雑であったり、わかりにくい部分のコメントアウトでの説明
 - [x] 命名規則の統一
 - [x] 変更箇所にエラーが発生してるかの確認
 - [] ビルドが成功するかの確認
## 問題

-ドアを敵が通り抜けるときに空いたり閉じたりはしないです。

2024-07-01 00:08 UTC, tibigamePoppo commented on Assets/Scripts/Scenes/InGame/Stage/StageDoor.cs
> +                Debug.LogWarning("�A�j���[�V�������ł�");
``` suggestion

``` 
なんか文字化けしてるのは治せそうですか

2024-07-02 04:49 UTC, IwamotoHinata requested changes

2024-07-02 04:49 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Enemy/EnemySpawner.cs
> +            }
```suggestion
        private async UniTaskVoid InitialSpawn(CancellationToken token) {
            //ドアを入手
           _doors = FindObjectsOfType<StageDoor>
            }
```
ドアって元々「StageIntract」ってタグが付いてたと思うのですが、できればEnemySpawnerでのドアの取得をタグで行うのではなく、FindObjectsOfTypeでStageDoorスクリプトの取得にはできませんか？

2024-07-02 04:58 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Enemy/EnemySpawner.cs
> +            }
提案のやつ駄目そうなので現在考え中。修正次第このコメント消します

2024-07-02 05:02 UTC, IwamotoHinata commented on Assets/Scripts/Scenes/InGame/Enemy/EnemySpawner.cs
> +            }
ドアについているタグは「StageIntract」に戻しておいてくれるとありがたいです

2024-07-05 12:33 UTC, Tyunousause commented on Assets/Scripts/Scenes/InGame/Enemy/EnemySpawner.cs
> +            }
プレハブのタグはいじっていないのでご安心を

2024-07-05 12:53 UTC, Tyunousause commented
レイヤー情報が何もかも破壊されているのでプルリク出しなおそうと思います

2024-07-09 16:10 UTC, closed without merging